(function(){
const R=window.KELO_TILE_REGISTRY,TERRAIN=window.KELO_TERRAIN_CONTRACT,G=window.KELO_GARDENS_ATLAS,J=window.KELO_GARDENS_JOINS;if(!R?.atlases||!R?.families||!TERRAIN?.materials||!TERRAIN?.transitions||!TERRAIN?.districts||!G||!J){console.error('[Kelo world] tile registry, terrain/district contract or gardens atlases missing');return;}
const TILE=R.worldTileSize||32,CHUNK=512,F=R.families,gardenImg=new Image(),gardenJoinImg=new Image(),cache=new Map(),MAX=24;let terrainReady=false,gardenReady=false,gardenJoinReady=false,ready=false;
const DISTRICTS=TERRAIN.districts;
const ROADS=Object.freeze([{x:384,y:1408,w:800,h:64},{x:1088,y:1408,w:96,h:160},{x:1088,y:1488,w:1792,h:96},{x:1376,y:384,w:128,h:2500},{x:1376,y:736,w:1120,h:128},{x:1376,y:2304,w:640,h:128}]);
const PADS=Object.freeze([{x:1888,y:1424,w:512,h:288},{x:1792,y:640,w:608,h:256}]);
const GARDEN_PATHS=Object.freeze([{x:1216,y:2304,w:160,h:64},{x:1504,y:2304,w:192,h:64},{x:1248,y:2368,w:64,h:192},{x:1600,y:2368,w:64,h:160},{x:1216,y:2528,w:128,h:96},{x:1568,y:2496,w:128,h:96},{x:1664,y:2432,w:32,h:64}]);
const GARDEN_PATH_CUTS=Object.freeze([{x:1216,y:2528,w:32,h:32},{x:1312,y:2528,w:32,h:32},{x:1216,y:2592,w:32,h:32},{x:1312,y:2592,w:32,h:32},{x:1568,y:2496,w:32,h:32},{x:1664,y:2496,w:32,h:32},{x:1568,y:2560,w:32,h:32},{x:1664,y:2560,w:32,h:32}]);
function inside(x,y,r){return x>=r.x&&y>=r.y&&x<r.x+r.w&&y<r.y+r.h}function gardenPath(x,y){return GARDEN_PATHS.some(r=>inside(x,y,r))&&!GARDEN_PATH_CUTS.some(r=>inside(x,y,r))}function road(x,y){return ROADS.some(r=>inside(x,y,r))||PADS.some(r=>inside(x,y,r))||gardenPath(x,y)}function district(x,y){return TERRAIN.districtForPoint?.(x,y)||DISTRICTS.find(d=>inside(x,y,d))||null}function profile(x,y){return TERRAIN.profileFor(district(x,y)?.id)}function terrainAt(x,y){const p=profile(x,y);return road(x,y)?p.pathTerrain:p.baseTerrain}function hash(x,y,s=0){return Math.abs(((x+17+s)*73856093)^((y+29+s)*19349663))}function pick(x,y,l){return l[hash(x,y)%l.length]}
function terrainAtlasKeys(){const keys=new Set();for(const def of Object.values(TERRAIN.materials)){if(def.atlas)keys.add(def.atlas);if(def.detailAtlas)keys.add(def.detailAtlas)}for(const set of Object.values(TERRAIN.transitions))if(set.atlas)keys.add(set.atlas);return Object.freeze([...keys])}
const TERRAIN_ATLAS_KEYS=terrainAtlasKeys(),ATLAS_IMAGES=Object.create(null);
for(const key of TERRAIN_ATLAS_KEYS){const atlas=R.atlases[key];if(!atlas){console.error('[Kelo world] terrain contract references missing atlas',key);return}ATLAS_IMAGES[key]={image:new Image(),atlas,ready:false}}
function atlasOrigin(atlas,id){const cols=atlas.columns||Math.floor(atlas.width/TILE);return{x:(id%cols)*TILE,y:Math.floor(id/cols)*TILE}}function drawAtlasTile(g,atlasKey,id,x,y){const entry=ATLAS_IMAGES[atlasKey];if(!entry?.ready||id==null)return false;const p=atlasOrigin(entry.atlas,id);g.drawImage(entry.image,p.x,p.y,TILE,TILE,x,y,TILE,TILE);return true}
function materialPool(def,profileDef,X,Y){const base=F[def.family]||[];if(!base.length)return base;if(profileDef.detailCluster&&Array.isArray(def.variationGroups)&&def.variationGroups.length){const macroX=Math.floor(X/3),macroY=Math.floor(Y/3),group=hash(macroX,macroY,131)%7===0?1:0;return def.variationGroups[Math.min(group,def.variationGroups.length-1)]||base}return base}
function drawMaterial(g,key,X,Y,dx,dy,profileDef){const def=TERRAIN.materials[key];if(!def)return false;const pool=materialPool(def,profileDef,X,Y);if(!pool.length)return false;let id=pick(X,Y,pool);if(profileDef.pathAccentEvery&&def.accentFamily&&F[def.accentFamily]?.length&&hash(X,Y,11)%profileDef.pathAccentEvery===0)id=pick(X+3,Y+7,F[def.accentFamily]);drawAtlasTile(g,def.atlas,id,dx,dy);if(profileDef.pathDetail&&def.detailAtlas&&def.detailFamily&&F[def.detailFamily]?.length){const detailId=pick(X+13,Y+5,F[def.detailFamily]);drawAtlasTile(g,def.detailAtlas,detailId,dx,dy)}return true}
const SIDE_STEPS=Object.freeze([{bit:TERRAIN.sideBits.top,dx:0,dy:-TILE},{bit:TERRAIN.sideBits.right,dx:TILE,dy:0},{bit:TERRAIN.sideBits.bottom,dx:0,dy:TILE},{bit:TERRAIN.sideBits.left,dx:-TILE,dy:0}]);
function transitionMask(wx,wy,set){let mask=0;for(const side of SIDE_STEPS)if(terrainAt(wx+TILE/2+side.dx,wy+TILE/2+side.dy)===set.neighbour)mask|=side.bit;return mask}
function drawTerrainTransitions(g,materialKey,wx,wy,dx,dy){for(const set of Object.values(TERRAIN.transitions)){if(set.owner!==materialKey)continue;const mask=transitionMask(wx,wy,set);if(!mask)continue;const frame=TERRAIN.frameFor(set.owner,set.neighbour,mask);if(frame!=null)drawAtlasTile(g,set.atlas,frame,dx,dy)}}
function gardenOrigin(id){return{x:(id%G.columns)*TILE,y:Math.floor(id/G.columns)*TILE}}function gardenJoinOrigin(id){return{x:(id%J.columns)*TILE,y:Math.floor(id/J.columns)*TILE}}function drawGarden(g,id,x,y){const p=gardenOrigin(id);g.drawImage(gardenImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE)}function drawGardenRotated(g,id,x,y,turns=0){const p=gardenOrigin(id),q=((turns%4)+4)%4;if(!q){g.drawImage(gardenImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE);return}g.save();g.translate(x+TILE/2,y+TILE/2);g.rotate(q*Math.PI/2);g.drawImage(gardenImg,p.x,p.y,TILE,TILE,-TILE/2,-TILE/2,TILE,TILE);g.restore()}function drawGardenJoin(g,id,x,y){const p=gardenJoinOrigin(id);g.drawImage(gardenJoinImg,p.x,p.y,TILE,TILE,x,y,TILE,TILE)}
const GT=G.tiles,JT=J.tiles,GC=R.styles?.gardensCompositions||null,GCM=new Map();function registerGardenCell(cell){const baseId=GT[cell[2]],joinId=JT[cell[2]],turns=cell[3];if(baseId!=null)GCM.set(cell[0]+','+cell[1],{atlas:'base',id:baseId,...(turns!=null?{turns}:{})});else if(joinId!=null)GCM.set(cell[0]+','+cell[1],{atlas:'join',id:joinId})}for(const comp of GC?.compositions||[])for(const cell of comp.cells||[])registerGardenCell(cell);for(const cell of GC?.fixedPlacements||[])registerGardenCell(cell);function gardenOverlay(X,Y){const lx=X-33,ly=Y-67;if(lx<0||ly<0||lx>=28||ly>=22)return null;if(lx>=20&&lx<=24&&ly>=9&&ly<=12)return null;const k=lx+','+ly;if(GCM.has(k))return GCM.get(k);if(hash(lx,ly,77)%29===0)return{atlas:'base',id:GT.FLOWER_TUFT};return null}
const TILE_OVERLAY_PROVIDERS=Object.freeze({'garden-compositions-v1':gardenOverlay});
function drawTileOverlay(g,visualProfile,terrainProfile,materialKey,X,Y,dx,dy){const providerId=visualProfile?.tileOverlayProvider;if(!providerId||materialKey!==terrainProfile.baseTerrain)return;const provider=TILE_OVERLAY_PROVIDERS[providerId];if(!provider)return;const ov=provider(X,Y);if(ov?.atlas==='join')drawGardenJoin(g,ov.id,dx,dy);else if(ov?.atlas==='base'&&ov.turns!=null)drawGardenRotated(g,ov.id,dx,dy,ov.turns);else if(ov?.atlas==='base')drawGarden(g,ov.id,dx,dy)}
function build(cx,cy){const key=cx+','+cy;if(cache.has(key))return cache.get(key);const c=document.createElement('canvas');c.width=CHUNK;c.height=CHUNK;const g=c.getContext('2d');g.imageSmoothingEnabled=false;const wx0=cx*CHUNK,wy0=cy*CHUNK,n=Math.ceil(CHUNK/TILE);for(let gy=0;gy<n;gy++)for(let gx=0;gx<n;gx++){const wx=wx0+gx*TILE,wy=wy0+gy*TILE,mx=wx+TILE/2,my=wy+TILE/2,X=Math.floor(wx/TILE),Y=Math.floor(wy/TILE),d=district(mx,my),vp=TERRAIN.districtVisualProfileFor(d?.id),p=TERRAIN.profileFor(d?.id),materialKey=terrainAt(mx,my);drawMaterial(g,materialKey,X,Y,gx*TILE,gy*TILE,p);drawTerrainTransitions(g,materialKey,wx,wy,gx*TILE,gy*TILE);drawTileOverlay(g,vp,p,materialKey,X,Y,gx*TILE,gy*TILE)}cache.set(key,c);if(cache.size>MAX)cache.delete(cache.keys().next().value);return c}
function bounds(){const z=window.CONFIG?.zoom||1,hw=(window.screenW||innerWidth)/(2*z)+CHUNK,hh=(window.screenH||innerHeight)/(2*z)+CHUNK,cam=window.camera||{x:1440,y:1520};return{minX:Math.max(0,Math.floor((cam.x-hw)/CHUNK)),maxX:Math.min(Math.ceil((window.CONFIG?.worldWidth||3600)/CHUNK)-1,Math.floor((cam.x+hw)/CHUNK)),minY:Math.max(0,Math.floor((cam.y-hh)/CHUNK)),maxY:Math.min(Math.ceil((window.CONFIG?.worldHeight||3200)/CHUNK)-1,Math.floor((cam.y+hh)/CHUNK))}}function updateDistrictAudit(){const cam=window.camera||{x:1440,y:1520},active=district(cam.x,cam.y);window.KELO_WORLD_AUDIT.activeDistrictLabel=active?.id||null}function draw(g){if(!ready)return false;const b=bounds();for(let y=b.minY;y<=b.maxY;y++)for(let x=b.minX;x<=b.maxX;x++)g.drawImage(build(x,y),x*CHUNK,y*CHUNK);updateDistrictAudit();return true}
function syncReady(){terrainReady=TERRAIN_ATLAS_KEYS.every(key=>ATLAS_IMAGES[key]?.ready===true);ready=terrainReady&&gardenReady&&gardenJoinReady;if(ready)Object.assign(window.KELO_WORLD_AUDIT,{ready:true,assetLoaded:true,transitionAssetLoaded:true,grassVariationAssetLoaded:true,marbleVariationAssetLoaded:true,gardensAssetLoaded:true,gardensJoinAssetLoaded:true,terrainAtlasesReady:true})}
function versionedSrc(src){return src+(src.includes('?')?'&':'?')+'world=191'}
for(const key of TERRAIN_ATLAS_KEYS){const entry=ATLAS_IMAGES[key],atlas=entry.atlas,image=entry.image;image.onload=()=>{if(image.naturalWidth!==atlas.width||image.naturalHeight!==atlas.height){console.error('[Kelo world] invalid terrain atlas dimensions',key,image.naturalWidth,image.naturalHeight);return}entry.ready=true;syncReady()};image.onerror=()=>console.error('[Kelo world] terrain atlas load failed',key);image.src=versionedSrc(atlas.src)}
gardenImg.onload=()=>{if(gardenImg.naturalWidth!==G.width||gardenImg.naturalHeight!==G.height){console.error('[Kelo world] invalid gardens atlas dimensions');return}gardenReady=true;syncReady()};gardenImg.onerror=()=>console.error('[Kelo world] gardens atlas load failed');gardenImg.src=G.src;gardenJoinImg.onload=()=>{if(gardenJoinImg.naturalWidth!==J.width||gardenJoinImg.naturalHeight!==J.height){console.error('[Kelo world] invalid gardens join atlas dimensions');return}gardenJoinReady=true;syncReady()};gardenJoinImg.onerror=()=>console.error('[Kelo world] gardens join atlas load failed');gardenJoinImg.src=J.src;
const commerceProfile=TERRAIN.profileFor('commerce');window.KELO_WORLD_AUDIT={version:'world-v1.23',ready:false,assetLoaded:false,transitionAssetLoaded:false,grassVariationAssetLoaded:false,marbleVariationAssetLoaded:false,gardensAssetLoaded:false,gardensJoinAssetLoaded:false,terrainAtlasesReady:false,terrainContractVersion:TERRAIN.version,districtVisualProfileVersion:TERRAIN.districtVisualProfileVersion,districtSourceMode:'terrain-contract-district-profiles-v2',districtOverlayMode:'profile-selected-provider-v1',terrainTopology:TERRAIN.topology,terrainMaterialCount:Object.keys(TERRAIN.materials).length,terrainTransitionSetCount:Object.keys(TERRAIN.transitions).length,terrainAtlasCount:TERRAIN_ATLAS_KEYS.length,terrainAtlasKeys:TERRAIN_ATLAS_KEYS,terrainRendererMode:'contract-driven-materials-v2',gardensMode:G.mode,gardensJoinMode:J.mode,gardensPathMode:'fountain-connected-promenade-v3',gardensTransitionMode:'authored-chamfered-path-topology-v1',gardensFramingMode:'registry-authored-modular-framing-v6',gardensCornerMode:'oriented-authored-corner-v1',gardensCornerOrientationCount:4,gardensFixedPlacementMode:GC?.fixedPlacementMode||null,gardensFixedPlacementCount:GC?.fixedPlacementCount||0,gardensCompositionMode:GC?.mode||null,gardensCompositionCount:GC?.compositionCount||0,gardensMarbleMode:R.styles?.marbleVariation?.mode||null,marbleVariationScope:R.styles?.marbleVariation?.scope||null,commerceMarbleVariation:commerceProfile.pathDetail===true,gardensGrassRhythmMode:'terrain-profile-variation-groups-v1',gardensLandmarkClearance:'east-fountain-footprint-v1',grassVariationMode:'authored-eight-variant-atlas-v1',grassVariationCount:(F.grassAuthored||[]).length,marbleVariationCount:(F.marbleVariation||[]).length,roadTransitionMode:'terrain-contract-edge-bitmask-v1',plazaRoadAlignment:'authored-plaza-ground-v1',districtLabelMode:'world-placards-removed-v1',activeDistrictLabel:null,chunkSize:CHUNK,districtCount:DISTRICTS.length,roadCount:ROADS.length+GARDEN_PATHS.length,districtStyleMode:'district-visual-profiles-v3',styledDistrictCount:Object.keys(TERRAIN.districtVisualProfiles).length,ruralRoadMode:'farm-bypass-v1',legacyTJunctionSpecialCase:false,worldWidth:window.CONFIG?.worldWidth||3600,worldHeight:window.CONFIG?.worldHeight||3200};window.KELO_WORLD_RENDERER=Object.freeze({draw,districts:DISTRICTS,chunkSize:CHUNK,get ready(){return ready}})
})();