(function(){
const R=window.KELO_TILE_REGISTRY;if(!R?.atlases?.plaza||!R?.families){console.error('[Kelo world] tile registry missing');return;}
const TILE=R.worldTileSize||32,CHUNK=512,A=R.atlases.plaza,F=R.families,COLS=A.columns,S=R.styles?.districtGround?.profiles||{},img=new Image(),cache=new Map(),MAX=24;let ready=false;
const DISTRICTS=Object.freeze([{id:'central',name:'Plaza Central',x:1040,y:1240,w:800,h:560,kind:'plaza'},{id:'rural',name:'Distrito Rural',x:448,y:1320,w:720,h:640,kind:'farm'},{id:'arena',name:'Distrito Arena',x:1728,y:448,w:864,h:640,kind:'arena'},{id:'commerce',name:'Distrito Comercio',x:1888,y:1264,w:896,h:704,kind:'commerce'},{id:'gardens',name:'Jardines del Sur',x:1056,y:2144,w:896,h:704,kind:'garden'}]);
// The rural marble branch bypasses the existing farm footprint instead of drawing beneath it.
const ROADS=Object.freeze([{x:384,y:1408,w:800,h:64},{x:1088,y:1408,w:96,h:192},{x:1088,y:1472,w:1792,h:128},{x:1376,y:384,w:128,h:2500},{x:1376,y:736,w:1120,h:128},{x:1376,y:2304,w:640,h:128}]);
const PADS=Object.freeze([{x:1888,y:1424,w:512,h:288},{x:1792,y:640,w:608,h:256},{x:1152,y:2240,w:704,h:352}]);
function inside(x,y,r){return x>=r.x&&y>=r.y&&x<r.x+r.w&&y<r.y+r.h}function road(x,y){return ROADS.some(r=>inside(x,y,r))||PADS.some(r=>inside(x,y,r))}function district(x,y){return DISTRICTS.find(d=>inside(x,y,d))||null}function style(x,y){const d=district(x,y);return S[d?.id]||S.default||{detailEvery:53,detailCluster:false,marbleAccentEvery:0}}function hash(x,y,s=0){return Math.abs(((x+17+s)*73856093)^((y+29+s)*19349663))}function pick(x,y,l){return l[hash(x,y)%l.length]}function detail(x,y,s){if(!F.grassDetail?.length||!s.detailEvery)return false;if(hash(x,y,5)%s.detailEvery===0)return true;return !!s.detailCluster&&(hash(x-1,y,5)%s.detailEvery===0||hash(x,y-1,5)%s.detailEvery===0)}function origin(id){return{x:(id%COLS)*TILE,y:Math.floor(id/COLS)*TILE}}function drawTile(g,id,x,y){const p=origin(id);g.drawImage(img,p.x,p.y,TILE,TILE,x,y,TILE,TILE)}
function build(cx,cy){const key=cx+','+cy;if(cache.has(key))return cache.get(key);const c=document.createElement('canvas');c.width=CHUNK;c.height=CHUNK;const g=c.getContext('2d');g.imageSmoothingEnabled=false;const wx0=cx*CHUNK,wy0=cy*CHUNK,n=Math.ceil(CHUNK/TILE);for(let gy=0;gy<n;gy++)for(let gx=0;gx<n;gx++){const wx=wx0+gx*TILE,wy=wy0+gy*TILE,mx=wx+TILE/2,my=wy+TILE/2,X=Math.floor(wx/TILE),Y=Math.floor(wy/TILE),st=style(mx,my);let id;if(road(mx,my)){id=pick(X,Y,F.marble);if(st.marbleAccentEvery&&F.marbleAccent?.length&&hash(X,Y,11)%st.marbleAccentEvery===0)id=pick(X+3,Y+7,F.marbleAccent)}else{id=pick(X,Y,F.grass);if(detail(X,Y,st))id=pick(X,Y,F.grassDetail)}drawTile(g,id,gx*TILE,gy*TILE)}cache.set(key,c);if(cache.size>MAX)cache.delete(cache.keys().next().value);return c}
function bounds(){const z=window.CONFIG?.zoom||1,hw=(window.screenW||innerWidth)/(2*z)+CHUNK,hh=(window.screenH||innerHeight)/(2*z)+CHUNK,cam=window.camera||{x:1440,y:1520};return{minX:Math.max(0,Math.floor((cam.x-hw)/CHUNK)),maxX:Math.min(Math.ceil((window.CONFIG?.worldWidth||3600)/CHUNK)-1,Math.floor((cam.x+hw)/CHUNK)),minY:Math.max(0,Math.floor((cam.y-hh)/CHUNK)),maxY:Math.min(Math.ceil((window.CONFIG?.worldHeight||3200)/CHUNK)-1,Math.floor((cam.y+hh)/CHUNK))}}
function labels(g){g.save();g.textAlign='center';g.font='bold 18px ui-monospace, monospace';DISTRICTS.forEach(d=>{const x=d.x+d.w/2,y=d.y+26;g.fillStyle='rgba(7,12,8,.72)';g.fillRect(x-92,y-18,184,26);g.fillStyle='#fff4cf';g.fillText(d.name,x,y)});g.restore()}
function draw(g){if(!ready)return false;const b=bounds();for(let y=b.minY;y<=b.maxY;y++)for(let x=b.minX;x<=b.maxX;x++)g.drawImage(build(x,y),x*CHUNK,y*CHUNK);labels(g);return true}
img.onload=()=>{if(img.naturalWidth!==A.width||img.naturalHeight!==A.height){console.error('[Kelo world] invalid atlas dimensions',img.naturalWidth,img.naturalHeight);return}ready=true;window.KELO_WORLD_AUDIT.ready=true;window.KELO_WORLD_AUDIT.assetLoaded=true};img.onerror=()=>console.error('[Kelo world] atlas load failed');img.src=A.src+'&world=171';
window.KELO_WORLD_AUDIT={version:'world-v1.1',ready:false,assetLoaded:false,chunkSize:CHUNK,districtCount:DISTRICTS.length,roadCount:ROADS.length,districtStyleMode:R.styles?.districtGround?.mode||null,styledDistrictCount:Object.keys(S).filter(k=>k!=='default').length,ruralRoadMode:'farm-bypass-v1',worldWidth:window.CONFIG?.worldWidth||3600,worldHeight:window.CONFIG?.worldHeight||3200};window.KELO_WORLD_RENDERER=Object.freeze({draw,districts:DISTRICTS,chunkSize:CHUNK,get ready(){return ready}})
})();