const { test, expect } = require('@playwright/test');
test('external Kenney tree reaches World Studio canvas and screenshot',async({page})=>{
  test.setTimeout(90000);
  await page.setViewportSize({width:390,height:844});
  await page.goto('/?mapEditor=1&externalTreeQA='+Date.now(),{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>window.KELO_ADMIN_KEYS?.can?.('world.edit',window.KELO_ADMIN_KEYS?.playerId?.()),null,{timeout:20000});
  await page.evaluate(()=>document.querySelector('#lx-side-menu')?.click());
  await page.waitForSelector('#lx-create-studio',{state:'attached',timeout:10000});
  await page.evaluate(()=>document.querySelector('#lx-create-studio')?.click());
  await page.waitForSelector('#kelo-creators-hub',{state:'visible'});
  await page.getByRole('button',{name:'Abrir World',exact:true}).click();
  await page.waitForSelector('#kelo-studio-live',{state:'visible',timeout:20000});
  await page.goto('/asset-vault.html?from=studio',{waitUntil:'domcontentloaded'});
  await page.locator('[data-chip][data-provider="kenney"][data-query="tree"]').first().click();
  await page.waitForFunction(()=>document.querySelectorAll('#explore-grid .card').length>0,null,{timeout:30000});
  const card=page.locator('#explore-grid .card').first();
  const name=(await card.locator('.name').textContent())?.trim();
  const provider=(await card.locator('.meta').textContent())?.trim();
  expect(provider.toLowerCase()).toContain('kenney');
  await card.locator('[data-act="preview"]').click();
  await expect(page.locator('#preview-modal')).toBeVisible();
  await page.locator('[data-preview-act="place"]').click();
  await page.waitForURL(/buildAsset=/,{timeout:30000});
  await page.waitForSelector('#kelo-studio-live',{state:'visible',timeout:30000});
  await page.waitForFunction(()=>/^(PLACEMENT|PREFAB)/.test(document.querySelector('#kelo-studio-live .ks-status')?.textContent||''),null,{timeout:30000});
  const before=await page.locator('#kelo-studio-live .ks-status').textContent();
  await page.mouse.click(195,420);
  await page.waitForTimeout(1800);
  const after=await page.locator('#kelo-studio-live .ks-status').textContent();
  expect(after).not.toBe(before);
  await page.screenshot({path:'test-results/external-library-tree-world.png',fullPage:false});
  console.log(JSON.stringify({asset:name,provider,status:after,screenshot:'test-results/external-library-tree-world.png'}));
});