const { test, expect } = require('@playwright/test');
test('external Kenney tree reaches World Studio canvas and screenshot',async({page})=>{
  test.setTimeout(90000);
  await page.setViewportSize({width:390,height:844});
  await page.goto('/asset-vault.html?from=studio',{waitUntil:'domcontentloaded'});
  await page.locator('[data-chip][data-provider="kenney"][data-query="tree"]').first().click();
  await page.waitForFunction(()=>document.querySelectorAll('#explore-grid .card').length>0,null,{timeout:30000});
  const card=page.locator('#explore-grid .card').first();
  const name=(await card.locator('.name').textContent())?.trim();
  const provider=(await card.locator('.meta').textContent())?.trim();
  expect(provider.toLowerCase()).toContain('kenney');
  await card.locator('[data-act="preview"]').click();
  await expect(page.locator('#preview-modal')).toBeVisible();
  await page.locator('[data-preview-act="place"]').click();
  await page.waitForURL(/buildAsset=/,{timeout:30000});
  await page.waitForSelector('#kelo-studio-live',{state:'visible',timeout:30000});
  await page.waitForTimeout(2500);
  const before=await page.evaluate(async()=>{const m=await import('./src/studio/studio-entry.mjs');return m.getKeloStudioSession?.()?.kernel?.document?.entities?.length||0;});
  await page.mouse.click(195,420);
  await page.waitForTimeout(2200);
  const after=await page.evaluate(async()=>{const m=await import('./src/studio/studio-entry.mjs');return m.getKeloStudioSession?.()?.kernel?.document?.entities?.length||0;});
  expect(after).toBeGreaterThan(before);
  await page.screenshot({path:'test-results/external-library-tree-world.png',fullPage:false});
  console.log(JSON.stringify({asset:name,provider,objects:after,screenshot:'test-results/external-library-tree-world.png'}));
});