/* KELO-INDEX
 * area: UI / GUARDIAN
 * owner: KeloGuardianUI
 * keys: GUARDIAN BUTTON DONATION GPU WEBGPU ASSET COMMUNITY CAPACITY BAR MASTER IPHONE SERVER HOST SAFE AREA WEBRTC HOT MIRROR FAILOVER RTT
 * purpose: panel in-game para donar recursos/GPU, ver capacidad comunitaria, observar P2P/Hot Mirror y, con permiso remoto, activar este dispositivo como Master Guardian foreground
 * online: UI solicita operaciones a KeloGuardian y solo lee KeloGuardianMirror/KeloGuardianGpuAssets; nunca concede permisos, rewards ni autoridad gameplay
 * do-not: NO mostrar master por confianza local; NO afirmar background continuo en iPhone; NO presentar GPU anunciada/hot mirror como autoridad PvP; NO llamar GPUu TFLOPS
 */
(function(root){
'use strict';
if(root.KeloGuardianUI||!root.KeloGuardian)return;
const OWNER='guardian-ui';let panel=null,lockToken=null,busy=false,message='',mirrorBootError='',candidateUrl='',candidateMeta=null;
const mirrorUrl=new URL('src/systems/guardian-hot-mirror.js?v=1',document.baseURI).href;
import(mirrorUrl).catch(error=>{mirrorBootError=String(error&&error.message||error);if(panel)render();});
function style(){if(document.getElementById('kelo-guardian-style'))return;const s=document.createElement('style');s.id='kelo-guardian-style';s.textContent=`
#kelo-guardian-button{position:fixed;right:max(10px,env(safe-area-inset-right));top:max(78px,calc(env(safe-area-inset-top) + 66px));z-index:115;border:1px solid rgba(231,197,106,.45);background:rgba(7,13,18,.92);color:#f4d986;border-radius:999px;padding:9px 12px;font:800 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 8px 26px rgba(0,0,0,.26);pointer-events:auto;backdrop-filter:blur(14px)}
#kelo-guardian-button[data-on="1"]{border-color:rgba(61,220,132,.65);color:#8ff0b7}#kelo-guardian-button[data-host="1"]{border-color:#f4d986;box-shadow:0 0 0 2px rgba(244,217,134,.16),0 8px 26px rgba(0,0,0,.3)}#kelo-guardian-button[data-mirror="1"]{box-shadow:0 0 0 2px rgba(73,157,255,.15),0 8px 26px rgba(0,0,0,.3)}
#kelo-guardian-sheet{position:fixed;inset:0;z-index:240;display:flex;align-items:flex-end;justify-content:center;padding:14px max(14px,env(safe-area-inset-right)) max(14px,env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));background:rgba(1,4,7,.52);pointer-events:auto}
#kelo-guardian-card{width:min(500px,100%);max-height:min(760px,calc(100dvh - 28px));overflow:auto;border:1px solid rgba(231,197,106,.28);border-radius:24px;background:linear-gradient(180deg,rgba(16,25,31,.98),rgba(6,11,15,.99));color:#eef4f0;padding:18px;box-shadow:0 28px 80px rgba(0,0,0,.52);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.kg-head{display:flex;align-items:center;gap:10px}.kg-head h2{font:900 20px/1.1 Georgia,serif;color:#f4d986;margin:0}.kg-close{margin-left:auto;border:0;background:rgba(255,255,255,.07);color:#fff;border-radius:999px;width:34px;height:34px;font-size:18px}.kg-status{margin:14px 0;padding:12px;border-radius:15px;background:rgba(255,255,255,.045);font-size:12px;line-height:1.45;color:#c8d4cf}.kg-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0}.kg-stat{padding:10px;border:1px solid rgba(255,255,255,.07);border-radius:13px;background:rgba(255,255,255,.025);min-width:0}.kg-stat b{display:block;color:#f1d786;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kg-stat b.good{color:#83edb0}.kg-stat b.blue{color:#87c4ff}.kg-stat span{font-size:10px;color:#8fa39b}.kg-action{width:100%;min-height:48px;margin-top:9px;border:1px solid rgba(231,197,106,.34);border-radius:14px;background:#172329;color:#f5dda0;font-weight:900;font-size:13px}.kg-action.primary{background:linear-gradient(180deg,#275844,#173c31);border-color:#56c98c;color:#eafff1}.kg-action.gpu{background:linear-gradient(180deg,#243958,#152238);border-color:#6599e8;color:#ddebff}.kg-action.master{background:linear-gradient(180deg,#6d5520,#3d2f13);border-color:#e7c56a;color:#fff2bd}.kg-action.danger{background:#2d1719;border-color:#a85158;color:#ffd4d7}.kg-action:disabled{opacity:.45}.kg-note{margin:12px 2px 2px;color:#8fa39b;font-size:11px;line-height:1.45}.kg-message{min-height:18px;margin-top:8px;color:#ffdda0;font-size:11px}.kg-pill{display:inline-flex;align-items:center;gap:5px;margin-top:8px;padding:5px 8px;border-radius:999px;background:rgba(83,187,132,.09);border:1px solid rgba(83,187,132,.22);color:#98efbc;font-size:10px;font-weight:800}.kg-pill.warn{background:rgba(231,197,106,.08);border-color:rgba(231,197,106,.2);color:#f0d989}
.kg-community{margin:12px 0;padding:13px;border:1px solid rgba(101,153,232,.22);border-radius:16px;background:rgba(36,57,88,.16)}.kg-community-head{display:flex;align-items:flex-end;justify-content:space-between;gap:10px}.kg-community-title{font-size:11px;font-weight:900;letter-spacing:.08em;color:#9fc5ff}.kg-community-big{font-size:19px;font-weight:950;color:#eef6ff}.kg-community-sub{font-size:10px;color:#91a6bb}.kg-capbar{height:11px;margin:10px 0 6px;border-radius:999px;background:rgba(255,255,255,.08);overflow:hidden}.kg-capfill{height:100%;border-radius:inherit;background:linear-gradient(90deg,#4d7fbd,#77b7ff);min-width:0}.kg-personal{display:flex;justify-content:space-between;gap:8px;margin-top:10px;font-size:10px;color:#b9c9d9}.kg-slider{width:100%;margin:9px 0 2px;accent-color:#77b7ff}.kg-gpu-state{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}.kg-preview{display:flex;gap:10px;align-items:center;margin-top:10px;padding:9px;border-radius:13px;background:rgba(255,255,255,.035)}.kg-preview img{width:64px;height:64px;image-rendering:pixelated;border-radius:9px;border:1px solid rgba(255,255,255,.12)}.kg-preview div{font-size:10px;color:#aebfca;line-height:1.45;min-width:0}.kg-preview b{display:block;color:#dcecff;font-size:11px}
`;document.head.appendChild(s);}
function state(){return root.KeloGuardian.state();}
function mirrorState(){try{return root.KeloGuardianMirror?.state?.()||null;}catch(_){return null;}}
function lock(){if(!lockToken&&root.KeloInputLocks)lockToken=root.KeloInputLocks.acquire(OWNER,{modal:true});}
function unlock(){if(lockToken&&root.KeloInputLocks)root.KeloInputLocks.release(lockToken);lockToken=null;}
function close(){if(panel){panel.remove();panel=null;}unlock();paintButton();}
function button(){let b=document.getElementById('kelo-guardian-button');if(b)return b;b=document.createElement('button');b.id='kelo-guardian-button';b.type='button';b.addEventListener('click',open);document.body.appendChild(b);return b;}
function paintButton(){const s=state(),m=mirrorState(),b=button();b.dataset.on=s.enabled?'1':'0';b.dataset.host=s.masterActive?'1':'0';b.dataset.mirror=m?.mode==='hot-mirror'?'1':'0';const gpu=s.preferences?.allowGpuAssets&&s.enabled?' · ⚡':'';b.textContent=s.masterActive?'👑 HOST'+gpu:m?.mode==='hot-mirror'?'🛡 MIRROR'+gpu:s.enabled?'🛡 GUARDIAN ON'+gpu:'🛡 GUARDIAN';}
function ageLabel(ms){if(!Number.isFinite(Number(ms)))return'—';const v=Math.max(0,Number(ms));return v<1000?Math.round(v)+' ms':(v/1000).toFixed(v<10000?1:0)+' s';}
function describeRole(s,m){if(s.masterActive)return`PRIMARY Guardian activo.${m?.backupCount?` ${m.backupCount} respaldo(s) están confirmando checkpoints.`:' Esperando mirrors conectados.'}`;if(m?.mode==='hot-mirror')return`HOT MIRROR listo. Último checkpoint observado hace ${ageLabel(m.checkpointAgeMs)}.`;if(m?.failoverCandidate)return'El enlace con el Master se perdió y este dispositivo está elegible para intentar relevo de lease.';if(s.connected)return'Nodo registrado: '+String(s.role||'donor-ready')+'. El coordinador decide qué trabajo útil asignar.';if(s.enabled)return'Donación activada; esperando registrar el nodo en el control plane.';return'Guardian está apagado en este dispositivo.';}
function mirrorLabel(m){if(!m)return'INICIANDO';if(m.mode==='primary')return'PRIMARY';if(m.mode==='hot-mirror')return'HOT MIRROR';if(m.failoverCandidate)return'FAILOVER';if(m.mode==='standby')return'STANDBY';return'OFF';}
function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function gpuCommunity(s){const n=s.network||{},g=s.localGpu||{},p=s.preferences||{},donors=Math.max(0,Math.floor(Number(n.gpuAssetDonors)||0)),capacity=Math.max(0,Number(n.gpuCapacityUnits)||0),target=Math.max(1,Number(n.gpuCapacityTargetUnits)||1000),pct=Math.max(0,Math.min(100,Number(n.gpuCapacityPct)||capacity/target*100)),share=Math.max(10,Math.min(100,Number(p.gpuSharePct)||25)),mine=s.enabled&&p.allowGpuAssets&&g.webgpu?Math.max(0,(Number(g.gpuCapacityUnits)||0)*share/100):0,gpuLabel=!g.webgpu?'NO DISPONIBLE':g.gpuTier==='detecting'?'DETECTANDO':String(g.gpuTier||'LISTA').toUpperCase(),enabled=!!(s.enabled&&p.allowGpuAssets),preview=candidateUrl&&candidateMeta?`<div class="kg-preview"><img src="${candidateUrl}" alt="Candidato procedural creado por Guardian GPU"><div><b>Asset candidato creado</b>${escapeHtml(candidateMeta.preset)} · ${candidateMeta.contributors} contribuidor(es)<br>${candidateMeta.verified?'✓ consenso de hash':'vista previa · requiere más validación'} · todavía pasa por Asset Forge QA</div></div>`:'';
return `<div class="kg-community"><div class="kg-community-head"><div><div class="kg-community-title">⚡ KELO COMMUNITY COMPUTE</div><div class="kg-community-sub">Jugadores ayudando a crear assets</div></div><div style="text-align:right"><div class="kg-community-big">${donors}</div><div class="kg-community-sub">donantes GPU activos</div></div></div><div class="kg-capbar" role="progressbar" aria-label="Capacidad GPU comunitaria" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${pct.toFixed(1)}"><div class="kg-capfill" style="width:${pct.toFixed(2)}%"></div></div><div class="kg-personal"><span><b>${capacity.toFixed(1)} GPUu</b> conectadas</span><span>meta de malla ${target.toFixed(0)} GPUu</span></div><div class="kg-gpu-state"><span class="kg-pill ${g.webgpu?'':'warn'}">GPU ${escapeHtml(gpuLabel)}</span><span class="kg-pill ${enabled?'':'warn'}">${enabled?'TÚ ESTÁS CONTRIBUYENDO':'APORTE GPU APAGADO'}</span></div><div class="kg-personal"><span>Tu aporte efectivo: <b>${mine.toFixed(1)} GPUu</b></span><span>${share}% de tu capacidad</span></div><input class="kg-slider" data-action="gpu-share" type="range" min="10" max="100" step="10" value="${share}" aria-label="Porcentaje máximo de GPU para assets" ${busy?'disabled':''}><button class="kg-action ${enabled?'danger':'gpu'}" data-action="gpu-toggle" ${busy||!g.webgpu?'disabled':''}>${enabled?'DETENER DONACIÓN GPU':'DONAR GPU PARA CREAR ASSETS'}</button>${s.masterActive&&enabled?`<button class="kg-action gpu" data-action="gpu-test" ${busy?'disabled':''}>⚡ CREAR TEXTURA COMUNITARIA DE PRUEBA</button>`:''}${preview}<div class="kg-note">GPUu es una unidad normalizada de capacidad conectada, no TFLOPS ni una recompensa. Los trabajos aceptan solo presets seguros; ningún jugador puede enviar shaders arbitrarios. Todo resultado es candidato y debe pasar QA antes de entrar al juego.</div></div>`;}
function render(){if(!panel)return;const s=state(),m=mirrorState(),network=s.network||{},dp=s.dataPlane||{},card=panel.querySelector('#kelo-guardian-card'),masterLabel=s.ios?'👑 USAR ESTE IPHONE COMO SERVER':'👑 USAR ESTE DISPOSITIVO COMO HOST',rtt=Number.isFinite(Number(dp.rttMs))?Math.round(Number(dp.rttMs))+' ms':'—',mirrorClass=m?.mode==='hot-mirror'||m?.mode==='primary'?'good':'',failover=m?.failoverCandidate?'READY':m?.claimInFlight?'CAMBIANDO':'—';
card.innerHTML=`<div class="kg-head"><div>🛡️</div><h2>Guardian</h2><button class="kg-close" aria-label="Cerrar">×</button></div><div class="kg-status"><strong>${s.enabled?'Donación activada':'Donación desactivada'}</strong><br>${describeRole(s,m)}${m?.checkpointFresh?`<div class="kg-pill">✓ checkpoint #${Number(m.latestSeq||0)} · tick ${Number(m.latestServerTick||0)}</div>`:''}${m?.failoverCandidate?'<div class="kg-pill warn">↻ relevo automático preparado</div>':''}</div>${gpuCommunity(s)}<div class="kg-grid"><div class="kg-stat"><b>${Number(network.activeNodes||0)}</b><span>Guardianes activos</span></div><div class="kg-stat"><b class="blue">${Number(dp.openPeerCount||0)}</b><span>P2P directos</span></div><div class="kg-stat"><b>${rtt}</b><span>RTT Guardian</span></div><div class="kg-stat"><b class="${mirrorClass}">${mirrorLabel(m)}</b><span>Redundancia</span></div><div class="kg-stat"><b>${Number(m?.backupCount||0)}</b><span>Mirrors confirmados</span></div><div class="kg-stat"><b>${failover}</b><span>Failover</span></div></div><button class="kg-action ${s.enabled?'danger':'primary'}" data-action="toggle" ${busy?'disabled':''}>${s.enabled?'APAGAR GUARDIAN':'ENCENDER GUARDIAN'}</button>${s.masterEligible?`<button class="kg-action master" data-action="master" ${busy?'disabled':''}>${s.masterActive?(s.ios?'DETENER IPHONE SERVER':'DETENER HOST'):masterLabel}</button>`:''}<div class="kg-message">${escapeHtml(message||m?.lastError||s.lastError||s.gpuWorkerError||mirrorBootError||'')}</div><div class="kg-note">Guardian distribuye trabajo útil sin entregar autoridad del juego. En iPhone, iOS puede suspender Kelo World con la pantalla bloqueada; el nodo deja de contar al expirar su heartbeat y la red continúa con otros Guardianes.</div>`;
card.querySelector('.kg-close').onclick=close;card.querySelector('[data-action="toggle"]').onclick=()=>act(async()=>s.enabled?root.KeloGuardian.deactivate():root.KeloGuardian.activate());const master=card.querySelector('[data-action="master"]');if(master)master.onclick=()=>act(async()=>s.masterActive?root.KeloGuardian.stopMasterHost():root.KeloGuardian.startMasterHost());const gpuToggle=card.querySelector('[data-action="gpu-toggle"]');if(gpuToggle)gpuToggle.onclick=()=>act(async()=>{const current=state(),turnOn=!(current.enabled&&current.preferences?.allowGpuAssets);if(turnOn){const cap=await root.KeloGuardian.gpuCapability(true);if(!cap.webgpu)throw new Error('WebGPU no está disponible en este dispositivo/navegador.');root.KeloGuardian.updatePreferences({allowGpuAssets:true});if(!current.enabled)await root.KeloGuardian.activate();await root.KeloGuardian.ensureGpuAssetWorker();}else root.KeloGuardian.updatePreferences({allowGpuAssets:false});});const share=card.querySelector('[data-action="gpu-share"]');if(share)share.addEventListener('change',()=>{root.KeloGuardian.updatePreferences({gpuSharePct:Number(share.value)});message='Tu límite GPU ahora es '+Number(share.value)+'%.';render();});const gpuTest=card.querySelector('[data-action="gpu-test"]');if(gpuTest)gpuTest.onclick=()=>act(async()=>{await root.KeloGuardian.ensureGpuAssetWorker();if(!root.KeloGuardianGpuAssets)throw new Error('Worker GPU no disponible.');const candidate=await root.KeloGuardianGpuAssets.requestProceduralAsset({preset:'material-noise-v1',width:32,height:32});if(candidateUrl)URL.revokeObjectURL(candidateUrl);candidateUrl=URL.createObjectURL(candidate.pngBlob);candidateMeta={preset:candidate.preset,contributors:candidate.contributors.length,verified:candidate.verifiedByQuorum};message='Asset candidato creado por la red Guardian.';});paintButton();}
async function act(fn){if(busy)return;busy=true;message='Procesando…';render();try{await fn();message=message==='Procesando…'?'Listo.':message;}catch(error){message=String(error&&error.message||error);}finally{busy=false;render();}}
function open(){if(panel)return;style();lock();panel=document.createElement('div');panel.id='kelo-guardian-sheet';panel.innerHTML='<div id="kelo-guardian-card"></div>';panel.addEventListener('pointerdown',ev=>{if(ev.target===panel)close();});document.body.appendChild(panel);message='';render();root.KeloGuardian.refresh().then(()=>root.KeloGuardian.gpuCapability(false)).then(render).catch(render);}
style();paintButton();root.addEventListener('kelo:guardian-state',()=>{paintButton();if(panel)render();},{passive:true});root.addEventListener('kelo:guardian-mirror-state',()=>{paintButton();if(panel)render();},{passive:true});root.addEventListener('kelo:guardian-gpu-ready',()=>{if(panel)render();},{passive:true});
root.KeloGuardianUI=Object.freeze({version:'kelo-guardian-ui-v3-community-gpu',open,close,render});
root.KELO_GUARDIAN_UI_AUDIT=Object.freeze({version:'kelo-guardian-ui-v3-community-gpu',inputLockOwner:OWNER,masterServerGated:true,iosBackgroundNotice:true,communityGpuMeter:true,gpuOptIn:true,gpuUnitsNormalized:true,mirrorReadOnly:true,gameplayAuthority:false});
})(typeof globalThis!=='undefined'?globalThis:window);