/* KELO-INDEX
 * area: UI / GUARDIAN
 * owner: KeloGuardianUI
 * keys: GUARDIAN BUTTON DONATION MASTER IPHONE SERVER HOST SAFE AREA
 * purpose: botón in-game para donar recursos y, solo para admin autorizado por server, activar este dispositivo como host Guardian foreground
 * online: UI solicita operaciones a KeloGuardian; nunca concede permisos ni cambia autoridad gameplay
 * do-not: NO mostrar master por confianza local; NO afirmar background continuo en iPhone
 */
(function(root){
'use strict';
if(root.KeloGuardianUI||!root.KeloGuardian)return;
const OWNER='guardian-ui';let panel=null,lockToken=null,busy=false,message='';
function style(){if(document.getElementById('kelo-guardian-style'))return;const s=document.createElement('style');s.id='kelo-guardian-style';s.textContent=`
#kelo-guardian-button{position:fixed;right:max(10px,env(safe-area-inset-right));top:max(78px,calc(env(safe-area-inset-top) + 66px));z-index:115;border:1px solid rgba(231,197,106,.45);background:rgba(7,13,18,.92);color:#f4d986;border-radius:999px;padding:9px 12px;font:800 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 8px 26px rgba(0,0,0,.26);pointer-events:auto;backdrop-filter:blur(14px)}
#kelo-guardian-button[data-on="1"]{border-color:rgba(61,220,132,.65);color:#8ff0b7}#kelo-guardian-button[data-host="1"]{border-color:#f4d986;box-shadow:0 0 0 2px rgba(244,217,134,.16),0 8px 26px rgba(0,0,0,.3)}
#kelo-guardian-sheet{position:fixed;inset:0;z-index:240;display:flex;align-items:flex-end;justify-content:center;padding:14px max(14px,env(safe-area-inset-right)) max(14px,env(safe-area-inset-bottom)) max(14px,env(safe-area-inset-left));background:rgba(1,4,7,.52);pointer-events:auto}
#kelo-guardian-card{width:min(480px,100%);border:1px solid rgba(231,197,106,.28);border-radius:24px;background:linear-gradient(180deg,rgba(16,25,31,.98),rgba(6,11,15,.99));color:#eef4f0;padding:18px;box-shadow:0 28px 80px rgba(0,0,0,.52);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.kg-head{display:flex;align-items:center;gap:10px}.kg-head h2{font:900 20px/1.1 Georgia,serif;color:#f4d986;margin:0}.kg-close{margin-left:auto;border:0;background:rgba(255,255,255,.07);color:#fff;border-radius:999px;width:34px;height:34px;font-size:18px}.kg-status{margin:14px 0;padding:12px;border-radius:15px;background:rgba(255,255,255,.045);font-size:12px;line-height:1.45;color:#c8d4cf}.kg-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.kg-stat{padding:10px;border:1px solid rgba(255,255,255,.07);border-radius:13px;background:rgba(255,255,255,.025)}.kg-stat b{display:block;color:#f1d786;font-size:14px}.kg-stat span{font-size:10px;color:#8fa39b}.kg-action{width:100%;min-height:48px;margin-top:9px;border:1px solid rgba(231,197,106,.34);border-radius:14px;background:#172329;color:#f5dda0;font-weight:900;font-size:13px}.kg-action.primary{background:linear-gradient(180deg,#275844,#173c31);border-color:#56c98c;color:#eafff1}.kg-action.master{background:linear-gradient(180deg,#6d5520,#3d2f13);border-color:#e7c56a;color:#fff2bd}.kg-action.danger{background:#2d1719;border-color:#a85158;color:#ffd4d7}.kg-action:disabled{opacity:.45}.kg-note{margin:12px 2px 2px;color:#8fa39b;font-size:11px;line-height:1.45}.kg-message{min-height:18px;margin-top:8px;color:#ffdda0;font-size:11px}`;document.head.appendChild(s);}
function state(){return root.KeloGuardian.state();}
function lock(){if(!lockToken&&root.KeloInputLocks)lockToken=root.KeloInputLocks.acquire(OWNER,{modal:true});}
function unlock(){if(lockToken&&root.KeloInputLocks)root.KeloInputLocks.release(lockToken);lockToken=null;}
function close(){if(panel){panel.remove();panel=null;}unlock();paintButton();}
function button(){let b=document.getElementById('kelo-guardian-button');if(b)return b;b=document.createElement('button');b.id='kelo-guardian-button';b.type='button';b.addEventListener('click',open);document.body.appendChild(b);return b;}
function paintButton(){const s=state(),b=button();b.dataset.on=s.enabled?'1':'0';b.dataset.host=s.masterActive?'1':'0';b.textContent=s.masterActive?'👑 HOST':s.enabled?'🛡 GUARDIAN ON':'🛡 GUARDIAN';}
function describeRole(s){if(s.masterActive)return'Este dispositivo tiene la lease de host Guardian mientras siga visible y enviando latidos.';if(s.connected)return'Nodo registrado: '+String(s.role||'donor-ready')+'. El coordinador decide qué trabajo útil asignar.';if(s.enabled)return'Donación activada; esperando registrar el nodo en el servidor.';return'Guardian está apagado en este dispositivo.';}
function render(){if(!panel)return;const s=state(),network=s.network||{},card=panel.querySelector('#kelo-guardian-card');const masterLabel=s.ios?'👑 USAR ESTE IPHONE COMO SERVER':'👑 USAR ESTE DISPOSITIVO COMO HOST';card.innerHTML=`<div class="kg-head"><div>🛡️</div><h2>Guardian</h2><button class="kg-close" aria-label="Cerrar">×</button></div><div class="kg-status"><strong>${s.enabled?'Donación activada':'Donación desactivada'}</strong><br>${describeRole(s)}</div><div class="kg-grid"><div class="kg-stat"><b>${Number(network.activeNodes||0)}</b><span>Guardianes activos</span></div><div class="kg-stat"><b>${Number(network.relayReady||0)}</b><span>Relay listos</span></div><div class="kg-stat"><b>${s.platform.toUpperCase()}</b><span>Este dispositivo</span></div><div class="kg-stat"><b>${s.masterActive?'HOST':'—'}</b><span>Rol especial</span></div></div><button class="kg-action ${s.enabled?'danger':'primary'}" data-action="toggle" ${busy?'disabled':''}>${s.enabled?'APAGAR GUARDIAN':'ENCENDER GUARDIAN'}</button>${s.masterEligible?`<button class="kg-action master" data-action="master" ${busy?'disabled':''}>${s.masterActive?(s.ios?'DETENER IPHONE SERVER':'DETENER HOST'):masterLabel}</button>`:''}<div class="kg-message">${message||s.lastError||''}</div><div class="kg-note">Donar en reposo queda guardado hasta que lo desactives. En iPhone, iOS puede suspender la app con la pantalla bloqueada; cuando el sistema deja de ejecutar la app, la lease expira y Guardian vuelve automáticamente al reabrir.</div>`;
card.querySelector('.kg-close').onclick=close;card.querySelector('[data-action="toggle"]').onclick=()=>act(async()=>s.enabled?root.KeloGuardian.deactivate():root.KeloGuardian.activate());const m=card.querySelector('[data-action="master"]');if(m)m.onclick=()=>act(async()=>s.masterActive?root.KeloGuardian.stopMasterHost():root.KeloGuardian.startMasterHost());paintButton();}
async function act(fn){if(busy)return;busy=true;message='Procesando…';render();try{await fn();message='Listo.';}catch(error){message=String(error&&error.message||error);}finally{busy=false;render();}}
function open(){if(panel)return;style();lock();panel=document.createElement('div');panel.id='kelo-guardian-sheet';panel.innerHTML='<div id="kelo-guardian-card"></div>';panel.addEventListener('pointerdown',ev=>{if(ev.target===panel)close();});document.body.appendChild(panel);message='';render();root.KeloGuardian.refresh().then(render).catch(render);}
style();paintButton();root.addEventListener('kelo:guardian-state',()=>{paintButton();if(panel)render();},{passive:true});
root.KeloGuardianUI=Object.freeze({version:'kelo-guardian-ui-v1',open,close,render});
root.KELO_GUARDIAN_UI_AUDIT=Object.freeze({version:'kelo-guardian-ui-v1',inputLockOwner:OWNER,masterServerGated:true,iosBackgroundNotice:true});
})(typeof globalThis!=='undefined'?globalThis:window);