/* KELO-INDEX
 * area: PVP / ARENA
 * owner: KeloArena
 * keys: ARENA RANKED MATCHMAKING MMR RP BOTS CONTROL OBJECTIVE NORMALIZED STATS AUTHORITY
 * purpose: cola única 3v3 Control con fallback local transparente de bots, rating visible+MMR oculto y contrato online reemplazable
 * public-api: openQueue/joinQueue/leaveQueue/finishMatch/abort/getHostileActors/getActorById/drawWorld/snapshot/getRank
 * consumes: KeloPvPWorld + KeloSimulation + KeloCombatEngine + KeloMeleeEngine + KeloEvents
 * state-owned: lifecycle de cola/match Arena, roster local fallback, objective score, rating fallback y bot decision state
 * extension-points: authority adapter, ruleSet, bot personality, objective modes, human matchmaking
 * reuse: los bots emiten decisiones hacia CombatEngine; no escriben daño directo
 * online: rating/matchmaking final deben ser server-authoritative; localStorage es fallback de prototipo con la misma boca pública
 * do-not: NO segundo combat engine, NO segundo loop, NO bots ocultos como humanos, NO farm de RP completo contra bots
 */
(function(root){
'use strict';
if(root.KeloArena)return;
const VERSION='kelo-arena-v1.0.0-ranked-control';
const STORAGE='kelo_arena_profile_v1';
const WORLD=Object.freeze({x:2660,y:360,w:720,h:720,cx:3020,cy:720});
const RULES=Object.freeze({id:'ranked_control_3v3_v1',teamSize:3,mode:'control',scoreToWin:100,duration:180,captureRadius:118,captureRate:11,respawnDelay:4,normalizedHp:100,normalizedMana:100,botAttackRange:145,botThinkInterval:.12,minimumRankedQuality:.2});
const TIERS=Object.freeze([
  Object.freeze({id:'bronze',label:'Bronce',min:0}),Object.freeze({id:'silver',label:'Plata',min:900}),Object.freeze({id:'gold',label:'Oro',min:1100}),Object.freeze({id:'platinum',label:'Platino',min:1300}),Object.freeze({id:'emerald',label:'Esmeralda',min:1500}),Object.freeze({id:'diamond',label:'Diamante',min:1700}),Object.freeze({id:'mithril',label:'Mithril',min:1900}),Object.freeze({id:'adamantite',label:'Adamantita',min:2150}),Object.freeze({id:'ethereal',label:'Etéreo',min:2400})
]);
const PERSONALITIES=Object.freeze({
  aggressor:Object.freeze({aggression:1.25,objective:.72,retreat:.25}),
  guardian:Object.freeze({aggression:.78,objective:1.25,retreat:.58}),
  tactician:Object.freeze({aggression:.92,objective:1.08,retreat:.48}),
  assassin:Object.freeze({aggression:1.18,objective:.66,retreat:.62}),
  support:Object.freeze({aggression:.68,objective:1.18,retreat:.74})
});
const BOT_NAMES=['Astra','Bram','Cyra','Doran','Eira','Fenn','Gala','Hiro','Iria','Juno'];
const state={status:'idle',queueStartedAt:0,match:null,profile:readProfile(),savedPlayer:null,originalSimulated:null,lastResult:null,error:null};
function clamp(n,a,b){return Math.max(a,Math.min(b,n));}
function now(){return typeof performance!=='undefined'&&performance.now?performance.now():Date.now();}
function readProfile(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(raw&&Number.isFinite(raw.mmr))return{mmr:clamp(Math.round(raw.mmr),0,4000),wins:Math.max(0,raw.wins|0),losses:Math.max(0,raw.losses|0),matches:Math.max(0,raw.matches|0)};}catch(_){}return{mmr:1000,wins:0,losses:0,matches:0};}
function persistProfile(){try{localStorage.setItem(STORAGE,JSON.stringify(state.profile));}catch(_){}}
function getRank(mmr){const value=Number.isFinite(Number(mmr))?Number(mmr):state.profile.mmr;let tier=TIERS[0],next=null;for(let i=0;i<TIERS.length;i++){if(value>=TIERS[i].min)tier=TIERS[i];else{next=TIERS[i];break;}}const floor=tier.min,ceil=next?next.min:Math.max(floor+300,2700),rp=Math.round(clamp((value-floor)/Math.max(1,ceil-floor),0,1)*100);return Object.freeze({id:tier.id,label:tier.label,mmr:Math.round(value),rp,next:next&&next.label||null});}
function isOnline(){return !!(root.KeloNetAuthority&&root.KeloNetAuthority.isOnline&&root.KeloNetAuthority.isOnline());}
function emit(name,detail){try{root.dispatchEvent(new CustomEvent('kelo:arena-'+name,{detail}));}catch(_){}try{if(root.KeloEvents)root.KeloEvents.emit('arena:'+name,detail);}catch(_){} }
function teamOf(actor){return actor&&actor._arenaTeam||null;}
function alive(actor){return !!(actor&&Number(actor.hp)>0&&!actor._arenaRespawning);}
function actorId(actor){return String(actor&&actor.id||'');}
function allActors(){return state.match?state.match.roster.map(r=>r.actor).filter(Boolean):[];}
function getActorById(id){const key=String(id||'');return allActors().find(a=>actorId(a)===key)||null;}
function getHostileActors(viewer){if(!state.match||state.status!=='active')return[];const team=teamOf(viewer)||'alpha';return allActors().filter(a=>a!==viewer&&teamOf(a)!==team&&alive(a));}
function normalizedSnapshot(actor){return{maxHp:Number(actor&&actor.maxHp)||100,hp:Number(actor&&actor.hp)||100,maxMana:Number(actor&&actor.maxMana)||100,mana:Number(actor&&actor.mana)||100};}
function applyNormalized(actor){if(!actor)return;actor.maxHp=RULES.normalizedHp;actor.hp=RULES.normalizedHp;actor.maxMana=RULES.normalizedMana;actor.mana=RULES.normalizedMana;}
function makeBot(index,team,spawn){const personalityKey=Object.keys(PERSONALITIES)[index%Object.keys(PERSONALITIES).length];return{id:'arena_bot_'+team+'_'+index,name:BOT_NAMES[index%BOT_NAMES.length]+' [Bot]',x:spawn.x,y:spawn.y,vx:0,vy:0,radius:20,hp:RULES.normalizedHp,maxHp:RULES.normalizedHp,mana:RULES.normalizedMana,maxMana:RULES.normalizedMana,gear:{bodyColor:team==='alpha'?'#5d84e8':'#d66d78',armorColor:'#e7c56a',weaponColor:'#fff'},_face:team==='alpha'?'right':'left',_gait:'idle',_arenaTeam:team,isArenaBot:true,botPersonality:personalityKey,_arenaAI:{think:0,attackCooldown:.2,respawn:0,targetId:null}};}
function spawnFor(team,slot){const left=team==='alpha',baseX=left?WORLD.x+115:WORLD.x+WORLD.w-115,baseY=WORLD.cy+(slot-1)*92;return{x:baseX,y:baseY};}
function buildLocalRoster(){const player=typeof localPlayer!=='undefined'?localPlayer:null;if(!player)throw new Error('ARENA_PLAYER_UNAVAILABLE');state.savedPlayer=normalizedSnapshot(player);player._arenaTeam='alpha';applyNormalized(player);const roster=[{actor:player,type:'human',team:'alpha',slot:0,playerKey:root.keloNet&&root.keloNet.playerKey||'local'}];for(let i=1;i<3;i++)roster.push({actor:makeBot(i,'alpha',spawnFor('alpha',i)),type:'bot',team:'alpha',slot:i});for(let i=0;i<3;i++)roster.push({actor:makeBot(i+3,'beta',spawnFor('beta',i)),type:'bot',team:'beta',slot:i});return roster;}
function beginLocalMatch(){if(state.status!=='matching')return false;let roster;try{roster=buildLocalRoster();}catch(e){state.status='idle';state.error=String(e);return false;}state.originalSimulated=typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)?simulatedPlayers.slice():null;if(typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)){simulatedPlayers.length=0;roster.filter(r=>r.type==='bot').forEach(r=>simulatedPlayers.push(r.actor));}state.match={id:'local_'+Date.now().toString(36),ruleSet:RULES,source:'local-fallback',startedAt:now(),elapsed:0,humanCount:1,quality:RULES.minimumRankedQuality,score:{alpha:0,beta:0},captureTeam:null,roster,winner:null};state.status='active';emit('match-started',snapshot());return true;}
function restoreWorld(){if(typeof localPlayer!=='undefined'&&state.savedPlayer){localPlayer.maxHp=state.savedPlayer.maxHp;localPlayer.hp=Math.min(state.savedPlayer.hp,state.savedPlayer.maxHp);localPlayer.maxMana=state.savedPlayer.maxMana;localPlayer.mana=Math.min(state.savedPlayer.mana,state.savedPlayer.maxMana);delete localPlayer._arenaTeam;}if(typeof simulatedPlayers!=='undefined'&&Array.isArray(simulatedPlayers)&&state.originalSimulated){simulatedPlayers.length=0;state.originalSimulated.forEach(a=>simulatedPlayers.push(a));}state.originalSimulated=null;state.savedPlayer=null;}
function expectedScore(own,other){return 1/(1+Math.pow(10,(other-own)/400));}
function applyResult(winner){const won=winner==='alpha',old=state.profile.mmr,enemy=1000,expected=expectedScore(old,enemy),quality=state.match?state.match.quality:RULES.minimumRankedQuality,delta=Math.round(30*((won?1:0)-expected)*quality);state.profile.mmr=clamp(old+delta,0,4000);state.profile.matches++;if(won)state.profile.wins++;else state.profile.losses++;persistProfile();return{won,delta,quality,rank:getRank(state.profile.mmr)};}
function finishMatch(winner,reason){if(!state.match||state.status!=='active')return null;winner=winner==='beta'?'beta':'alpha';state.match.winner=winner;const result=applyResult(winner);state.lastResult=Object.freeze({winner,reason:reason||'score',delta:result.delta,quality:result.quality,rank:result.rank,score:Object.freeze({...state.match.score})});state.status='finished';emit('match-finished',snapshot());return state.lastResult;}
function cleanupAfterFinish(){restoreWorld();state.match=null;state.status='idle';if(root.KeloPvPWorld&&root.KeloPvPWorld.state&&root.KeloPvPWorld.state.combatEnabled)root.KeloPvPWorld.leave();emit('idle',snapshot());}
function abort(reason){if(state.status==='idle')return false;restoreWorld();state.lastResult=Object.freeze({aborted:true,reason:reason||'cancelled'});state.match=null;state.status='idle';emit('aborted',snapshot());return true;}
function joinQueue(){if(state.status!=='idle')return Promise.resolve(snapshot());state.status='queued';state.queueStartedAt=now();state.error=null;emit('queue-changed',snapshot());if(isOnline()&&root.KeloNetAuthority&&typeof root.KeloNetAuthority.requestArena==='function'){state.status='matching';return root.KeloNetAuthority.requestArena('join',{ruleSetId:RULES.id}).then(server=>{emit('server-queue',server);return snapshot();}).catch(()=>{state.status='queued';return startLocalFallback();});}return Promise.resolve(startLocalFallback());}
function startLocalFallback(){state.status='matching';if(!root.KeloPvPWorld||typeof root.KeloPvPWorld.enter!=='function'){state.status='idle';state.error='PVP_WORLD_UNAVAILABLE';return snapshot();}root.KeloPvPWorld.enter();emit('queue-changed',snapshot());return snapshot();}
function leaveQueue(){if(state.status==='queued'||state.status==='matching'){state.status='idle';state.queueStartedAt=0;emit('queue-changed',snapshot());return true;}return false;}
function nearestEnemy(bot){const list=allActors().filter(a=>a!==bot&&teamOf(a)!==teamOf(bot)&&alive(a));list.sort((a,b)=>Math.hypot(a.x-bot.x,a.y-bot.y)-Math.hypot(b.x-bot.x,b.y-bot.y));return list[0]||null;}
function moveToward(bot,point,speed,dt){const dx=point.x-bot.x,dy=point.y-bot.y,d=Math.hypot(dx,dy)||1;if(d<5){bot._gait='idle';return;}bot.x+=dx/d*speed*dt;bot.y+=dy/d*speed*dt;bot._face=Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down');bot._gait='run';bot.x=clamp(bot.x,WORLD.x+24,WORLD.x+WORLD.w-24);bot.y=clamp(bot.y,WORLD.y+24,WORLD.y+WORLD.h-24);}
function botAttack(bot,target){if(!root.KeloCombatEngine||!root.KeloMeleeEngine)return false;const profile=root.KeloMeleeEngine.getProfile&&root.KeloMeleeEngine.getProfile('sword_light_basic');if(!profile)return false;const dx=target.x-bot.x,dy=target.y-bot.y,l=Math.hypot(dx,dy)||1,dir={x:dx/l,y:dy/l};const result=root.KeloCombatEngine.attackSweep({attacker:bot,targets:[target],direction:dir,profile,profileId:profile.id,attackId:'arena_bot_'+Date.now().toString(36)+'_'+bot.id,startedAt:now(),source:'arena-bot',skipStart:false});return !!(result&&result.hits&&result.hits.length);}
function respawn(actor,row,dt){if(alive(actor))return false;actor._arenaRespawning=true;actor._arenaRespawnLeft=Number(actor._arenaRespawnLeft)||RULES.respawnDelay;actor._arenaRespawnLeft-=dt;if(actor._arenaRespawnLeft>0)return true;const s=spawnFor(row.team,row.slot);actor.x=s.x;actor.y=s.y;actor.hp=actor.maxHp=RULES.normalizedHp;actor.mana=actor.maxMana=RULES.normalizedMana;actor._arenaRespawning=false;actor._arenaRespawnLeft=0;if(actor._arenaAI)actor._arenaAI.attackCooldown=.5;return true;}
function updateBot(row,dt){const bot=row.actor,ai=bot._arenaAI;if(respawn(bot,row,dt))return;ai.attackCooldown=Math.max(0,ai.attackCooldown-dt);ai.think-=dt;if(ai.think>0)return;ai.think=RULES.botThinkInterval;const p=PERSONALITIES[bot.botPersonality]||PERSONALITIES.tactician,target=nearestEnemy(bot);if(!target)return;ai.targetId=target.id;const distance=Math.hypot(target.x-bot.x,target.y-bot.y),hpRatio=bot.hp/Math.max(1,bot.maxHp),objective={x:WORLD.cx,y:WORLD.cy};let destination=objective;if(hpRatio<p.retreat*.35){const awayX=bot.x+(bot.x-target.x),awayY=bot.y+(bot.y-target.y);destination={x:awayX,y:awayY};}else if(distance<RULES.botAttackRange*1.35&&p.aggression>=p.objective*.72)destination=target;moveToward(bot,destination,118*(.88+p.aggression*.12),RULES.botThinkInterval);if(distance<=RULES.botAttackRange&&ai.attackCooldown<=0){botAttack(bot,target);ai.attackCooldown=.72+(1.15-p.aggression)*.18;}}
function updateObjective(dt){const inside={alpha:0,beta:0};state.match.roster.forEach(row=>{const a=row.actor;if(!alive(a))return;if(Math.hypot(a.x-WORLD.cx,a.y-WORLD.cy)<=RULES.captureRadius)inside[row.team]++;});const owner=inside.alpha>0&&inside.beta===0?'alpha':inside.beta>0&&inside.alpha===0?'beta':null;state.match.captureTeam=owner;if(owner){state.match.score[owner]=clamp(state.match.score[owner]+RULES.captureRate*dt,0,RULES.scoreToWin);if(state.match.score[owner]>=RULES.scoreToWin)finishMatch(owner,'control-score');}}
function tick(ctx){const dt=clamp(Number(ctx&&ctx.dt)||0,0,.05);if(state.status==='matching'){if(root.KeloPvPWorld&&root.KeloPvPWorld.state&&root.KeloPvPWorld.state.combatEnabled)beginLocalMatch();return;}if(state.status==='finished'){cleanupAfterFinish();return;}if(state.status!=='active'||!state.match)return;if(!root.KeloPvPWorld||!root.KeloPvPWorld.state||!root.KeloPvPWorld.state.combatEnabled){abort('pvp-left');return;}state.match.elapsed+=dt;state.match.roster.filter(r=>r.type==='bot').forEach(r=>updateBot(r,dt));state.match.roster.filter(r=>r.type==='human').forEach(r=>respawn(r,r,dt));updateObjective(dt);if(state.status==='active'&&state.match.elapsed>=RULES.duration){const a=state.match.score.alpha,b=state.match.score.beta;finishMatch(a===b?'alpha':a>b?'alpha':'beta','time');}}
function drawWorld(ctx){if(state.status!=='active'||!state.match||!ctx)return false;ctx.save();ctx.fillStyle='rgba(55,169,213,.08)';ctx.strokeStyle='rgba(104,210,255,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(WORLD.cx,WORLD.cy,RULES.captureRadius,0,Math.PI*2);ctx.fill();ctx.stroke();state.match.roster.forEach(row=>{const a=row.actor;if(row.type==='human'||!a||a._arenaRespawning)return;if(typeof renderAvatar==='function')renderAvatar(a,false);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(a.x-30,a.y-50,60,6);ctx.fillStyle=row.team==='alpha'?'#64a7ff':'#ef6d7a';ctx.fillRect(a.x-30,a.y-50,60*clamp(a.hp/a.maxHp,0,1),6);ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText(a.name,a.x,a.y-57);});ctx.restore();return true;}
function snapshot(){const rank=getRank();const m=state.match;return Object.freeze({version:VERSION,status:state.status,ruleSet:RULES,rank,profile:Object.freeze({wins:state.profile.wins,losses:state.profile.losses,matches:state.profile.matches}),match:m?Object.freeze({id:m.id,source:m.source,elapsed:m.elapsed,humanCount:m.humanCount,quality:m.quality,score:Object.freeze({...m.score}),captureTeam:m.captureTeam,winner:m.winner,roster:Object.freeze(m.roster.map(r=>Object.freeze({id:actorId(r.actor),name:r.actor.name,type:r.type,team:r.team,hp:Number(r.actor.hp)||0,maxHp:Number(r.actor.maxHp)||100}))) }):null,lastResult:state.lastResult,error:state.error});}
if(!root.KeloSimulation)throw new Error('KeloArena requires KeloSimulation');
root.KeloSimulation.after('arena:ranked-control',tick,72);
root.KeloArena=Object.freeze({version:VERSION,rules:RULES,tiers:TIERS,joinQueue,openQueue:joinQueue,leaveQueue,finishMatch,abort,getHostileActors,getActorById,drawWorld,snapshot,getRank,isActive:()=>state.status==='active'});
root.KELO_ARENA_AUDIT=Object.freeze({version:VERSION,owner:'KeloArena',singleQueue:true,teamSize:3,mode:'control',transparentBots:true,botsUseCombatEngine:true,normalizedStats:true,hiddenMmr:true,visibleRank:true,matchQualityWeightedRp:true,onlineAuthorityBoundary:true,localFallback:true,secondLoop:false});
emit('ready',snapshot());
})(typeof globalThis!=='undefined'?globalThis:window);
