(function(){
'use strict';
const VERSION='armor-aura-v1.0';
const THRESHOLDS=[0,330,475,750,950,1350,1720,2225,3860,5250];
const PARTICLES=[0,0,2,4,5,6,8,10,12,16];
function rankFromScore(score){score=Math.max(0,Math.floor(Number(score)||0));let r=0;for(let i=1;i<THRESHOLDS.length;i++)if(score>=THRESHOLDS[i])r=i;return r;}
function rankOf(player){if(!player)return 0;if(Number.isFinite(player.auraRank))return Math.max(0,Math.min(9,Math.floor(player.auraRank)));if(window.KeloEquipment){const score=player===localPlayer?window.KeloEquipment.getArmorScore():Number(player.armorScore)||0;return window.KeloEquipment.getAuraRank(score);}return rankFromScore(player.armorScore||0);}
function phase(player,salt){const id=String(player&&player.id||'p');let h=0;for(let i=0;i<id.length;i++)h=(h*31+id.charCodeAt(i))>>>0;return (performance.now()*0.001+(h%97)*0.07+(salt||0));}
function drawRing(ctx,p,rank,front){if(rank<=0)return;const t=phase(p,rank),pulse=1+Math.sin(t*2.2)*(.025+rank*.004),rx=(p.radius||20)*(1.05+rank*.075)*pulse,ry=rx*.38;ctx.save();ctx.globalAlpha=Math.min(.16+rank*.045,.58);ctx.strokeStyle=rank>=8?'#ffe69a':'#d8b75b';ctx.lineWidth=rank>=7?2.2:1.4;ctx.beginPath();ctx.ellipse(p.x,p.y+(p.radius||20)*.72,rx,ry,0,front?0:Math.PI,front?Math.PI:Math.PI*2);ctx.stroke();if(rank>=7){ctx.globalAlpha*=.58;ctx.beginPath();ctx.ellipse(p.x,p.y+(p.radius||20)*.72,rx*1.2,ry*1.35,0,front?0:Math.PI,front?Math.PI:Math.PI*2);ctx.stroke();}ctx.restore();}
function drawBodyGlow(ctx,p,rank){if(rank<3)return;const t=phase(p,2),r=(p.radius||20)*(1.35+rank*.07+Math.sin(t*1.7)*.025);ctx.save();ctx.globalAlpha=.035+rank*.012;ctx.fillStyle=rank>=8?'#fff0b3':'#e7c56a';ctx.beginPath();ctx.arc(p.x,p.y-(p.radius||20)*.2,r,0,Math.PI*2);ctx.fill();ctx.restore();}
function drawParticles(ctx,p,rank,front){if(rank<5)return;const count=PARTICLES[rank]||0,t=phase(p,5),rad=(p.radius||20)*(1.1+rank*.06);ctx.save();ctx.fillStyle=rank>=8?'#ffeaa0':'#e7c56a';for(let i=0;i<count;i++){if((i%2===0)!==front)continue;const a=(i/count)*Math.PI*2+t*(.16+(i%3)*.025),rise=((t*.35+i*.137)%1),x=p.x+Math.cos(a)*rad*(.45+.55*rise),y=p.y+(p.radius||20)*.6-rise*(p.radius||20)*2.3;const s=rank>=9&&i%5===0?2.1:1.15;ctx.globalAlpha=.12+.42*(1-rise);ctx.fillRect(Math.round(x-s/2),Math.round(y-s/2),s,s);}ctx.restore();}
function drawSpark(ctx,p,rank){if(rank<9)return;const t=phase(p,9);ctx.save();ctx.strokeStyle='#fff2ba';ctx.globalAlpha=.45+.22*Math.sin(t*3);ctx.lineWidth=1;for(let i=0;i<3;i++){const a=t*.55+i*Math.PI*2/3,r=(p.radius||20)*1.45,x=p.x+Math.cos(a)*r,y=p.y-(p.radius||20)*.25+Math.sin(a)*r*.55;ctx.beginPath();ctx.moveTo(x-3,y);ctx.lineTo(x+3,y);ctx.moveTo(x,y-3);ctx.lineTo(x,y+3);ctx.stroke();}ctx.restore();}
function renderBack(ctx,p){const rank=rankOf(p);if(!rank)return;drawRing(ctx,p,rank,false);drawBodyGlow(ctx,p,rank);drawParticles(ctx,p,rank,false);}
function renderFront(ctx,p){const rank=rankOf(p);if(!rank)return;drawRing(ctx,p,rank,true);drawParticles(ctx,p,rank,true);drawSpark(ctx,p,rank);}
function install(){if(typeof renderAvatar!=='function'||renderAvatar.__keloArmorAura)return false;const base=renderAvatar;const wrapped=function(p,isSelf){renderBack(ctx,p);base(p,isSelf);renderFront(ctx,p);};wrapped.__keloArmorAura=true;renderAvatar=wrapped;return true;}
install();
window.KeloArmorAura=Object.freeze({version:VERSION,thresholds:THRESHOLDS.slice(),particleBudget:PARTICLES.slice(),getAuraRank:rankFromScore,rankOf,renderBack,renderFront,install});
window.KELO_ARMOR_AURA_AUDIT={version:VERSION,ready:true,maxRank:9,maxParticles:16,canvasOnly:true,thresholds:THRESHOLDS.slice()};
})();