/* KELO-INDEX
 * area: CORE / BOOT
 * owner: KeloModuleLoader
 * keys: DYNAMIC LOAD FIRST-USE MOBILE SAFARI RECOVERY QUARANTINE STYLE ASSET-LIBRARY FEATURE-REGISTRY FUSEBOX CIRCUIT-BREAKER PVP LEGACY-FALLBACK
 * purpose: un solo hilo de descarga lazy; carga FuseBox al primer uso opcional y mantiene fallback legacy fuera del first-playable
 * public-api: KELO_MODULE_LOADER.start/ensure/needs/isReady/canLoad/features/diagnostics
 * consumes: KELO_FEATURE_REGISTRY + KELO_ASSET_REGISTRY + lazy KELO_FUSEBOX + lazy legacy fallback + KELO_RECOVERY_MESH + KeloRuntimeBootstrap
 * do-not: NO segundo loader/gameLoop, NO prefetch pesado, NO polling, NO segundo circuit breaker
 */
(function(root){
'use strict';
if(root.KELO_MODULE_LOADER)return;
const VERSION='kelo-module-loader-v13-lazy-fusebox';
const LEGACY_IDS=Object.freeze(['social','world','pvp','bag','mounts','market','titles','appearance','properties']);
const loaded=Object.create(null),inflight=Object.create(null),failures=Object.create(null);
let build='V6.69',shown=false,fuseBoot=null,legacyBoot=null,legacy=null;
function registry(){return root.KELO_FEATURE_REGISTRY||null;}
function fusebox(){return root.KELO_FUSEBOX||null;}
function resolveName(name){const raw=String(name||''),r=registry();if(r&&typeof r.resolve==='function')return r.resolve(raw);return raw==='nobility'||raw==='emotes'?'social':raw;}
function featureIds(){const r=registry();return r&&Array.isArray(r.ids)?r.ids.slice():LEGACY_IDS.slice();}
function featureSpec(name){const r=registry();return r&&typeof r.get==='function'?r.get(name):null;}
function filesFor(name){return featureSpec(name)?.files||legacy?.[name]||null;}
function dependenciesFor(name){const spec=featureSpec(name);return Array.isArray(spec?.dependencies)?spec.dependencies:[];}
function emit(type,detail){try{root.dispatchEvent(new CustomEvent(type,{detail:Object.freeze({...detail})}));}catch(_){}try{root.KELO_RECOVERY_MESH?.mark?.(String(type).replace(/^kelo:/,'').replace(/-/g,'_').toUpperCase(),detail);}catch(_){}}
function recoveryQuery(){try{return new URLSearchParams(root.location?.search||'');}catch(_){return null;}}
function quarantined(name){const q=recoveryQuery();if(!q||!(q.get('recoveryLab')==='1'||q.get('debugRecovery')==='1'||q.get('freezeLab')==='1'))return false;try{if(root.KELO_RECOVERY_MESH?.shouldSkip?.(name))return true;}catch(_){}return String(q.get('recoverySkip')||'').split(',').map(v=>v.trim()).filter(Boolean).includes(String(name));}
function assetAllowed(name){try{return !root.KELO_ASSET_REGISTRY?.isEnabled||root.KELO_ASSET_REGISTRY.isEnabled(name)!==false;}catch(_){return true;}}
function fuseAllowed(name){try{return !fusebox()?.canRun||fusebox().canRun(name)!==false;}catch(_){return true;}}
function composedAllowed(name){return assetAllowed(name)&&fuseAllowed(name);}
function begin(name){try{return !fusebox()?.beginAttempt||fusebox().beginAttempt(name)!==false;}catch(_){return true;}}
function success(name){try{fusebox()?.recordSuccess?.(name,{operation:'module-load'});}catch(_){}}
function failure(name,errors){try{fusebox()?.recordFailure?.(name,new Error('MODULE_FEATURE_LOAD_FAILED'),{operation:'module-load',code:'MODULE_FEATURE_LOAD_FAILED',message:String(errors)+' file load error(s)'});}catch(_){}}
function cancel(name,reason){try{fusebox()?.cancelAttempt?.(name,reason);}catch(_){}}
function fuseBlocked(name){let gate=null;try{gate=fusebox()?.explain?.(name)||null;}catch(_){}emit('kelo:module-blocked',{feature:name,src:'',ok:false,error:'FUSEBOX_'+String(gate?.status||'BLOCKED'),retryAt:Number(gate?.retryAt)||0});}
function busy(){try{return typeof input!=='undefined'&&input&&(Math.abs(input.normX)>0.02||Math.abs(input.normY)>0.02||input.active);}catch(_){return false;}}
function box(){return document.getElementById('kelo-module-loader');}
function show(msg,pct){const el=box();if(!el)return;el.hidden=false;shown=true;const t=document.getElementById('kelo-ml-text'),b=document.getElementById('kelo-ml-bar');if(t)t.textContent=msg;if(b)b.style.width=Math.max(0,Math.min(100,pct||0))+'%';}
function hideChip(msg){const el=box();if(!el)return;if(shown){show(msg||'Listo',100);setTimeout(()=>{el.hidden=true;},800);}else el.hidden=true;}
function base(src){return String(src||'').split('?')[0];}
function hasAsset(item){const target=base(item.src);return item.type==='style'?Array.from(document.querySelectorAll('link[rel="stylesheet"]')).some(link=>base(link.getAttribute('href'))===target):Array.from(document.scripts).some(script=>base(script.getAttribute('src'))===target);}
function loadOne(item,feature){return new Promise(resolve=>{if(hasAsset(item)){emit('kelo:module-load-end',{feature,src:item.src,type:item.type||'script',ok:true,ms:0,cached:true});resolve({ms:0,ok:true,cached:true});return;}const t0=performance.now(),type=item.type==='style'?'style':'script',node=type==='style'?document.createElement('link'):document.createElement('script');emit('kelo:module-load-start',{feature,src:item.src,name:item.name,type});if(type==='style'){node.rel='stylesheet';node.href=item.src;}else{node.src=item.src;node.async=false;}node.onload=()=>{const ms=performance.now()-t0;emit('kelo:module-load-end',{feature,src:item.src,type,ok:true,ms:Math.round(ms),cached:false});resolve({ms,ok:true,cached:false});};node.onerror=()=>{const ms=performance.now()-t0;failures[item.src]=(failures[item.src]||0)+1;emit('kelo:module-load-error',{feature,src:item.src,type,ok:false,ms:Math.round(ms),error:type==='style'?'STYLE_LOAD_ERROR':'SCRIPT_LOAD_ERROR',count:failures[item.src]});resolve({ms,ok:false,cached:false});};document.head.appendChild(node);});}
function ensureLegacy(){if(registry()||legacy)return Promise.resolve(true);if(legacyBoot)return legacyBoot;legacyBoot=loadOne({src:'src/core/module-loader-legacy-fallback.js?v=1',name:'compatibilidad loader'},'loader-compat').then(r=>{legacy=root.__KELO_MODULE_LOADER_LEGACY_FALLBACK__||null;return r.ok&&!!legacy;});return legacyBoot;}
function ensureFuse(){if(fusebox())return Promise.resolve(true);if(fuseBoot)return fuseBoot;fuseBoot=loadOne({src:'src/core/feature-control-system.js?v=1',name:'FuseBox'},'feature-control').then(r=>r.ok&&!!fusebox());return fuseBoot;}
function prepare(){return ensureLegacy().then(ok=>ok===false?false:ensureFuse());}
function loadFeature(name,opts){name=resolveName(name);const files=filesFor(name);if(!files)return Promise.resolve(true);if(!assetAllowed(name)){emit('kelo:module-blocked',{feature:name,src:'',ok:false,error:'ASSET_LIBRARY_DISABLED'});return Promise.resolve(false);}if(!fuseAllowed(name)){fuseBlocked(name);return Promise.resolve(false);}if(quarantined(name)){emit('kelo:module-quarantined',{feature:name,src:'',ok:false,error:'RECOVERY_QUARANTINE'});return Promise.resolve(false);}if(loaded[name])return Promise.resolve(true);if(inflight[name])return inflight[name];if(!begin(name)){fuseBlocked(name);return Promise.resolve(false);}const interactive=!!opts?.interactive;inflight[name]=new Promise(resolve=>{let i=0,errors=0;function step(){if(!assetAllowed(name)){cancel(name,'asset-library-disabled-during-load');delete inflight[name];emit('kelo:module-blocked',{feature:name,src:'',ok:false,error:'ASSET_LIBRARY_DISABLED_DURING_LOAD'});resolve(false);return;}if(i>=files.length){const ok=errors===0;loaded[name]=ok;delete inflight[name];if(ok){try{localStorage.setItem('kelo_modpack_'+name,build);}catch(_){}success(name);}else failure(name,errors);emit('kelo:module-feature-complete',{feature:name,ok,files:files.length,errors});resolve(ok);return;}if(!interactive&&busy()){if(shown)show('En pausa · caminando',(i/files.length)*100);setTimeout(step,450);return;}const item=files[i];loadOne(item,name).then(result=>{const dt=Number(result?.ms)||0;if(!result?.ok)errors++;if(dt>=50)show('Descargando '+item.name+'  '+(i+1)+'/'+files.length,((i+1)/files.length)*100);i++;setTimeout(step,dt<50?80:360);});}step();});return inflight[name];}
function ensureDependencies(name){let chain=Promise.resolve(true);for(const dep of dependenciesFor(name))chain=chain.then(ok=>ok===false?false:loadFeature(resolveName(dep),{interactive:true}));return chain;}
function pvpDomainReady(){return !!(root.KeloPvPWorld&&typeof root.enterPvPWorld==='function'&&root.KELO_PVP_COMBAT_LOADER_AUDIT?.ready===true);}
function ensurePvp(){if(pvpDomainReady())return Promise.resolve(true);if(!filesFor('pvp'))return Promise.resolve(false);if(!assetAllowed('pvp')){emit('kelo:module-blocked',{feature:'pvp',src:'',ok:false,error:'ASSET_LIBRARY_DISABLED'});hideChip('PvP desactivado en Assets');return Promise.resolve(false);}if(!fuseAllowed('pvp')){fuseBlocked('pvp');hideChip('PvP temporalmente aislado');return Promise.resolve(false);}if(quarantined('pvp')){emit('kelo:module-quarantined',{feature:'pvp',src:'',ok:false,error:'RECOVERY_QUARANTINE'});return Promise.resolve(false);}show('Cargando PvP…',8);const foundations=root.KeloRuntimeBootstrap?.ensure?root.KeloRuntimeBootstrap.ensure():Promise.reject(new Error('KELO_RUNTIME_BOOTSTRAP_UNAVAILABLE'));return foundations.then(()=>loadFeature('pvp',{interactive:true})).then(ok=>{const ready=ok!==false&&pvpDomainReady();if(!ready){loaded.pvp=false;emit('kelo:module-load-error',{feature:'pvp',src:'',type:'runtime',ok:false,error:'PVP_RUNTIME_INCOMPLETE'});}hideChip(ready?'PvP listo':'Fallo al cargar PvP');return ready;}).catch(error=>{loaded.pvp=false;emit('kelo:module-load-error',{feature:'pvp',src:'',type:'runtime',ok:false,error:String(error?.message||error)});hideChip('Fallo al cargar PvP');throw error;});}
function ensureManaged(name){if(name==='pvp')return ensurePvp();name=resolveName(name);if(!filesFor(name))return Promise.resolve(true);if(!assetAllowed(name)){emit('kelo:module-blocked',{feature:name,src:'',ok:false,error:'ASSET_LIBRARY_DISABLED'});hideChip('Desactivado en Assets');return Promise.resolve(false);}if(!fuseAllowed(name)){fuseBlocked(name);hideChip('Módulo temporalmente aislado');return Promise.resolve(false);}if(quarantined(name)){emit('kelo:module-quarantined',{feature:name,src:'',ok:false,error:'RECOVERY_QUARANTINE'});return Promise.resolve(false);}show('Cargando '+name+'…',8);return ensureDependencies(name).then(ok=>ok===false?false:loadFeature(name,{interactive:true})).then(ok=>{hideChip(ok?'Listo':'Fallo al cargar');return ok;});}
function ensure(name){if(name==='chat'||name==='profile')return Promise.resolve(true);return prepare().then(ok=>ok===false?false:ensureManaged(name));}
function needs(name){if(name==='chat'||name==='profile')return false;if(name==='pvp')return !pvpDomainReady();name=resolveName(name);if(!registry()&&!legacy)return LEGACY_IDS.includes(name);if(!filesFor(name))return false;return !composedAllowed(name)||!loaded[name];}
function start(opts){if(opts?.build)build=String(opts.build);const el=box();if(el)el.hidden=true;emit('kelo:module-loader-start',{build,version:VERSION,registryVersion:registry()?.version||'legacy-fallback',assetSelection:root.KELO_ASSET_REGISTRY?.getState?.().features||null});}
function diagnostics(){const ids=featureIds();return Object.freeze({version:VERSION,registryVersion:registry()?.version||'legacy-fallback',build,features:ids,enabled:ids.filter(composedAllowed),disabled:ids.filter(k=>!composedAllowed(k)),loaded:Object.keys(loaded).filter(k=>loaded[k]),inflight:Object.keys(inflight),failures:{...failures},quarantined:ids.filter(quarantined),pvpReady:pvpDomainReady(),fusebox:fusebox()?.diagnostics?.()||null});}
root.KELO_MODULE_LOADER=Object.freeze({version:VERSION,start,ensure,needs,isReady:n=>{const name=resolveName(n);return name==='pvp'?pvpDomainReady():!!loaded[name];},canLoad:composedAllowed,features:featureIds(),diagnostics});
})(typeof globalThis!=='undefined'?globalThis:window);
