/* KELO-INDEX
 * area: CORE / POST-BOOT
 * owner: KeloUpdateGate
 * keys: UPDATE GATE VERSION WATCH LAZY TURBO V7 MOBILE SAFARI HOT CLASSIFIER FAST-FORWARD
 * purpose: detect builds cheaply, classify exact commit deltas, hot-apply safe CSS-only changes, skip non-runtime deploys, and wake verified updater only when restart is required
 * public-api: KeloUpdateGate.checkNow/wakeHeavy/getState/learnHotset
 * state-owned: one timeout + lightweight build state + compact resource hotset + short-lived compare seed + update policy
 * do-not: NO arbitrary JS hot swap, NO asset tree walk, NO Service Worker, NO setInterval, NO second loop, NO gameplay state
 */
(function(root){
'use strict';
if(root.KeloUpdateGate)return;
const VERSION='kelo-update-gate-v7-update-classes';
const STORAGE_KEY='kelo.world.updater.installedBuild.v1';
const LAST_GOOD_KEY='kelo.world.updater.lastGoodBuild.v5';
const PENDING_KEY='kelo.world.updater.pendingBuild.v5';
const LEGACY_PENDING_KEY='kelo.world.updater.pendingBuild.v4';
const POLICY_KEY='kelo.world.updater.policy.v1';
const HOTSET_KEY='kelo.world.updater.hotset.v1';
const COMPARE_CACHE_PREFIX='kelo.world.updater.compare.v5.';
const COMPARE_API='https://api.github.com/repos/kelffren/gemini/compare/';
const BUILD_RE=/^[0-9a-f]{7,64}$/i;
const BLOB_RE=/^[0-9a-f]{40,64}$/i;
const FAST_CHECK_MS=5000,STEADY_CHECK_MS=15000,FAST_WINDOW_MS=120000,BUSY_RETRY_MS=4000,FIRST_CHECK_DELAY_MS=650,VERSION_TIMEOUT_MS=3500,COMPARE_TIMEOUT_MS=5000,HOT_STYLE_TIMEOUT_MS=5000,HOTSET_LIMIT=80;
const startedAt=Date.now(),baseUrl=new URL('./',document.baseURI);
const FULL_RESTART_EXACT=new Set(['index.html','sw.js','manifest.webmanifest','engine-a.js','engine-b.js','engine-c.js','src/core/kelo-runtime-bootstrap.js','src/core/input-lock-system.js','src/core/player-state-system.js','src/core/player-position-system.js','src/core/camera-system.js','src/core/module-loader.js','src/core/feature-registry.js','src/core/asset-registry.js','src/core/update-gate.js','src/core/update-system-v5.js','src/core/update-watch.js','src/core/session-continuity-system.js','src/core/session-continuity-retry.js','src/physics/collision-utils.js']);
let timer=0,checking=false,heavyLoading=null,heavyReady=!!root.KeloUpdater,stopped=false,lastDeployed=null,lastError=null,lastReason='boot',hotsetLearnedAt=0,lastFastForward=null,lastClassification=null;
function normalize(v){v=String(v||'').trim();return BUILD_RE.test(v)?v.toLowerCase():null;}
function normalizeBlob(v){v=String(v||'').trim();return BLOB_RE.test(v)?v.toLowerCase():null;}
function installed(){try{return normalize(localStorage.getItem(STORAGE_KEY));}catch(_){return null;}}
function parsePending(raw){if(!raw)return null;try{const j=JSON.parse(raw);return normalize(j&&j.build);}catch(_){return normalize(raw);}}
function pending(){try{return parsePending(sessionStorage.getItem(PENDING_KEY))||parsePending(sessionStorage.getItem(LEGACY_PENDING_KEY));}catch(_){return null;}}
function migrateLegacyPending(){try{const raw=sessionStorage.getItem(LEGACY_PENDING_KEY),b=parsePending(raw);if(!b||sessionStorage.getItem(PENDING_KEY))return;sessionStorage.setItem(PENDING_KEY,JSON.stringify({build:b,previous:installed(),attempts:0,startedAt:Date.now(),migratedFrom:'v4'}));sessionStorage.removeItem(LEGACY_PENDING_KEY);}catch(_){} }
function setHint(deployed,current,reason){try{root.__KELO_UPDATE_HINT__={deployedBuild:normalize(deployed),installedBuild:normalize(current),detectedAt:Date.now(),reason:String(reason||'gate'),classification:lastClassification};}catch(_){} }
function emit(type,detail){try{root.dispatchEvent(new CustomEvent('kelo:update-gate:'+type,{detail:Object.assign(getState(),detail||{})}));}catch(_){} }
function readJson(raw){try{return raw?JSON.parse(raw):null;}catch(_){return null;}}
function getState(){return Object.freeze({version:VERSION,installedBuild:installed(),pendingBuild:pending(),deployedBuild:lastDeployed,checking,heavyLoading:!!heavyLoading,heavyReady:!!root.KeloUpdater||heavyReady,lastError,lastReason,stopped,nextCheckMs:nextDelay(),hotsetLearnedAt,lastFastForward,lastClassification});}
function clear(){if(timer){clearTimeout(timer);timer=0;}}
function nextDelay(){return Date.now()-startedAt<FAST_WINDOW_MS?FAST_CHECK_MS:STEADY_CHECK_MS;}
function schedule(ms){if(stopped||heavyReady||root.KeloUpdater)return;clear();timer=setTimeout(function(){void checkNow();},Math.max(500,Number(ms)||nextDelay()));}
function gameplayBusy(){if(document.visibilityState!=='visible'||navigator.onLine===false)return true;if(root.KELO_COMBAT_ENABLED===true)return true;try{if(root.KeloArena?.isActive?.())return true;}catch(_){}try{if(typeof input!=='undefined'&&input&&(input.active||Math.abs(input.normX)>0.02||Math.abs(input.normY)>0.02))return true;}catch(_){}try{const d=root.KELO_MODULE_LOADER?.diagnostics?.();if(d&&Array.isArray(d.inflight)&&d.inflight.length)return true;}catch(_){}return false;}
function repoPath(value){try{const u=new URL(value,baseUrl);if(u.origin!==baseUrl.origin||!u.pathname.startsWith(baseUrl.pathname))return null;return decodeURIComponent(u.pathname.slice(baseUrl.pathname.length).replace(/^\/+/,''))||'index.html';}catch(_){return null;}}
function observedResources(){const out=new Map();try{performance.getEntriesByType('resource').forEach(function(e){const name=e&&e.name;if(!name||!/\.(?:js|mjs|css|json|woff2?|ttf|otf)(?:[?#].*)?$/i.test(name))return;const path=repoPath(name);if(!path)return;const u=new URL(name,baseUrl);u.hash='';out.set(path,{path,url:u.href});});}catch(_){}return out;}
function learnHotset(){try{const current=readJson(localStorage.getItem(HOTSET_KEY)),previous=new Map((current&&Array.isArray(current.items)?current.items:[]).filter(Boolean).map(x=>[x.path,x])),now=Date.now(),observed=observedResources();for(const e of observed.values()){const old=previous.get(e.path)||{path:e.path,url:e.url,hits:0,lastSeen:0};old.url=e.url;old.hits=Math.min(999,Number(old.hits||0)+1);old.lastSeen=now;previous.set(e.path,old);}const items=Array.from(previous.values()).sort((a,b)=>(Number(b.hits)||0)-(Number(a.hits)||0)||(Number(b.lastSeen)||0)-(Number(a.lastSeen)||0)).slice(0,HOTSET_LIMIT);localStorage.setItem(HOTSET_KEY,JSON.stringify({version:1,updatedAt:now,items}));hotsetLearnedAt=now;emit('hotset-learned',{count:items.length,observed:observed.size});return items;}catch(_){return [];}}
function compareCacheKey(base,head){return COMPARE_CACHE_PREFIX+String(base).slice(0,16)+'.'+String(head).slice(0,16);}
function compactFiles(files){return (files||[]).map(f=>({filename:f&&f.filename||null,previous_filename:f&&f.previous_filename||null,status:f&&f.status||null,sha:normalizeBlob(f&&f.sha)})).filter(f=>f.filename);}
function nonRuntimePath(path){const p=String(path||'').replace(/^\/+/, '');return p.startsWith('.github/')||p.startsWith('docs/')||p.startsWith('scripts/')||/^(?:README|LICENSE|CHANGELOG|CONTRIBUTING)(?:\.|$)/i.test(p)||/\.(?:md|markdown)$/i.test(p);}
function criticalPath(path){const p=String(path||'').replace(/^\/+/, '');return FULL_RESTART_EXACT.has(p)||p.startsWith('src/core/events/');}
function uniquePaths(files){const out=new Set();for(const f of files||[]){if(f&&f.filename)out.add(String(f.filename));if(f&&f.previous_filename)out.add(String(f.previous_filename));}return Array.from(out);}
function classify(files){const paths=uniquePaths(files),runtimePaths=paths.filter(p=>!nonRuntimePath(p));let mode='seamless-restart',reason='runtime-change';if(!runtimePaths.length){mode='none';reason='non-runtime-only';}else if(runtimePaths.every(p=>/\.css$/i.test(p))){mode='hot';reason='css-only';}else if(runtimePaths.some(criticalPath)){mode='full-restart';reason='critical-runtime-owner';}const result=Object.freeze({mode,reason,paths,runtimePaths,at:Date.now()});lastClassification=result;return result;}
function writePolicy(classification,build){try{sessionStorage.setItem(POLICY_KEY,JSON.stringify({v:1,build:normalize(build),mode:classification.mode,reason:classification.reason,runtimePaths:classification.runtimePaths.slice(0,80),at:Date.now()}));}catch(_){} }
function clearPolicy(){try{sessionStorage.removeItem(POLICY_KEY);}catch(_){} }
function cacheCompare(base,head,status,files){try{sessionStorage.setItem(compareCacheKey(base,head),JSON.stringify({at:Date.now(),status:status||null,files}));return true;}catch(_){return false;}}
async function compareBuilds(base,head){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),COMPARE_TIMEOUT_MS),started=performance.now();try{const url=COMPARE_API+encodeURIComponent(base)+'...'+encodeURIComponent(head),r=await fetch(url,{cache:'no-cache',headers:{accept:'application/vnd.github+json'},priority:'low',signal:controller.signal});if(!r.ok)throw new Error('compare_http_'+r.status);const json=await r.json(),raw=Array.isArray(json&&json.files)?json.files:null;if(!raw||raw.length>=300)return {ok:false,reason:'compare_too_large',files:[]};const files=compactFiles(raw);cacheCompare(base,head,json.status,files);return {ok:true,status:json.status||null,files,ms:Math.round(performance.now()-started)};}catch(error){return {ok:false,reason:String(error&&error.message||error),files:[],ms:Math.round(performance.now()-started)};}finally{clearTimeout(timeout);}}
function hotStyleLink(path){return Array.from(document.querySelectorAll('link[rel~="stylesheet"][href]')).find(link=>repoPath(link.href)===path)||null;}
function swapStyle(link,path,build){return new Promise((resolve,reject)=>{if(!link){resolve({path,loaded:false,reason:'not-resident'});return;}const next=link.cloneNode(true),u=new URL(link.href,baseUrl);u.searchParams.set('kelo_hot',String(build).slice(0,16));next.href=u.href;next.dataset.keloHotBuild=String(build).slice(0,16);const timeout=setTimeout(()=>{cleanup();try{next.remove();}catch(_){}reject(new Error('hot_css_timeout:'+path));},HOT_STYLE_TIMEOUT_MS);function cleanup(){clearTimeout(timeout);next.onload=null;next.onerror=null;}next.onload=()=>{cleanup();try{link.remove();}catch(_){}resolve({path,loaded:true});};next.onerror=()=>{cleanup();try{next.remove();}catch(_){}reject(new Error('hot_css_load_failed:'+path));};link.parentNode.insertBefore(next,link.nextSibling);});}
async function applyHot(classification,deployed){if(gameplayBusy())return false;const results=[];try{for(const path of classification.runtimePaths)results.push(await swapStyle(hotStyleLink(path),path,deployed));try{localStorage.setItem(STORAGE_KEY,deployed);localStorage.setItem(LAST_GOOD_KEY,deployed);}catch(_){}clearPolicy();lastFastForward={build:deployed,files:classification.paths.length,at:Date.now(),mode:'hot',reload:false};lastReason='hot-applied';emit('classified',{build:deployed,classification});emit('hot-applied',{build:deployed,classification,results,reload:false});try{root.dispatchEvent(new CustomEvent('kelo:update:hot-applied',{detail:{build:deployed,classification,results}}));}catch(_){}schedule(nextDelay());return true;}catch(error){lastError=String(error&&error.message||error);lastClassification=Object.freeze({mode:'seamless-restart',reason:'hot-fallback',paths:classification.paths,runtimePaths:classification.runtimePaths,at:Date.now(),error:lastError});writePolicy(lastClassification,deployed);emit('hot-fallback',{build:deployed,error:lastError,classification:lastClassification});return false;}}
async function tryFastForward(current,deployed){if(!current||!deployed||current===deployed)return false;const compared=await compareBuilds(current,deployed);if(!compared.ok){lastClassification=Object.freeze({mode:'seamless-restart',reason:'compare-unavailable',paths:[],runtimePaths:[],at:Date.now()});writePolicy(lastClassification,deployed);emit('compare-seed-error',{build:deployed,error:compared.reason,compareMs:compared.ms});return false;}const classification=classify(compared.files);emit('compare-seeded',{build:deployed,files:compared.files.length,compareMs:compared.ms,classification});emit('classified',{build:deployed,classification});if(classification.mode==='none'){try{localStorage.setItem(STORAGE_KEY,deployed);localStorage.setItem(LAST_GOOD_KEY,deployed);}catch(_){}clearPolicy();lastFastForward={build:deployed,files:compared.files.length,at:Date.now(),compareMs:compared.ms,mode:'none',reload:false};lastReason='fast-forward';emit('fast-forward',{build:deployed,files:compared.files.length,compareMs:compared.ms,downloadedBytes:0,reload:false,classification});schedule(nextDelay());return true;}if(classification.mode==='hot')return applyHot(classification,deployed);writePolicy(classification,deployed);return false;}
function load(src){return new Promise((resolve,reject)=>{const base=src.split('?')[0],existing=Array.from(document.scripts).find(s=>String(s.getAttribute('src')||'').split('?')[0]===base);if(existing){resolve();return;}const s=document.createElement('script');s.src=src;s.async=false;s.dataset.keloUpdateGate='1';s.onload=resolve;s.onerror=()=>reject(new Error('update_gate_script_load_failed:'+src));document.head.appendChild(s);});}
function wakeHeavy(reason){if(root.KeloUpdater){heavyReady=true;stopped=true;clear();return Promise.resolve(root.KeloUpdater);}if(heavyLoading)return heavyLoading;lastReason=String(reason||'manual');clear();try{learnHotset();}catch(_){}emit('heavy-start',{reason:lastReason,classification:lastClassification});heavyLoading=load('src/core/update-system-v5.js?v=5.1-health-hint').then(()=>load('src/core/update-watch.js?v=3')).then(()=>{if(!root.KeloUpdater)throw new Error('updater_missing_after_load');heavyReady=true;stopped=true;clear();lastError=null;emit('heavy-ready',{reason:lastReason,classification:lastClassification});try{root.dispatchEvent(new CustomEvent('kelo:update:connected',{detail:{version:'turbo-v5.1',mode:'verified-predictive-gate',reason:lastReason,classification:lastClassification}}));}catch(_){}return root.KeloUpdater;}).catch(error=>{lastError=String(error&&error.message||error);emit('heavy-error',{error:lastError});schedule(BUSY_RETRY_MS);throw error;}).finally(()=>{heavyLoading=null;});return heavyLoading;}
async function deployedBuild(){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),VERSION_TIMEOUT_MS);try{const u=new URL('version.json',document.baseURI);u.searchParams.set('_kelo_gate',Date.now().toString(36));const r=await fetch(u.href,{cache:'no-cache',credentials:'same-origin',priority:'low',signal:controller.signal});if(!r.ok)throw new Error('version_http_'+r.status);const json=await r.json(),build=normalize(json&&json.sha);if(!build)throw new Error('version_missing_sha');return build;}finally{clearTimeout(timeout);}}
async function checkNow(){if(stopped||heavyReady||root.KeloUpdater)return getState();if(checking)return getState();if(gameplayBusy()){lastReason='busy';schedule(BUSY_RETRY_MS);return getState();}checking=true;lastReason='checking';emit('checking',{});try{const deployed=await deployedBuild();lastDeployed=deployed;lastError=null;const current=installed(),resume=pending(),requested=normalize(new URL(root.location.href).searchParams.get('kelo_update'));if(resume||requested||!current){lastReason=resume||requested?'apply-resume':'first-install';setHint(deployed,current,lastReason);emit('heavy-needed',{reason:lastReason});await wakeHeavy(lastReason);return getState();}if(current!==deployed){lastReason='new-build';emit('available',{build:deployed});if(await tryFastForward(current,deployed))return getState();const mode=lastClassification?.mode||'seamless-restart';lastReason=mode;setHint(deployed,current,mode);await wakeHeavy(mode);return getState();}lastReason='current';clearPolicy();emit('current',{build:deployed});schedule(nextDelay());}catch(error){lastError=String(error&&error.message||error);lastReason='check-error';emit('error',{error:lastError});schedule(BUSY_RETRY_MS);}finally{checking=false;}return getState();}
function start(){migrateLegacyPending();if(root.KeloUpdater){heavyReady=true;stopped=true;return;}const arm=()=>{setTimeout(()=>{try{learnHotset();}catch(_){}},2500);if(pending()){schedule(0);return;}schedule(FIRST_CHECK_DELAY_MS);};if(document.readyState==='complete')arm();else root.addEventListener('load',arm,{once:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule(250);else try{learnHotset();}catch(_){} });root.addEventListener('online',()=>schedule(250));root.addEventListener('pagehide',()=>{try{learnHotset();}catch(_){}},{capture:false});}
root.KeloUpdateGate=Object.freeze({version:VERSION,checkNow,wakeHeavy,getState,learnHotset});
root.KELO_UPDATE_CLASSIFIER_AUDIT=Object.freeze({version:VERSION,modes:Object.freeze(['none','hot','seamless-restart','full-restart']),hotPolicy:'css-only',arbitraryJsHotSwap:false,classificationSource:'github-compare-delta'});
start();
})(typeof globalThis!=='undefined'?globalThis:window);
