/* KELO-INDEX
 * area: GATHERING / FISHING LIVE
 * owner: KeloFishingLive
 * purpose: physical world fishing with cast, bite, timing challenge, rarity and backpack catch
 * consumes: KeloSimulation/KeloRender/KeloCamera/KeloPlayerPosition/KeloContainers
 * do-not: NO second loop, NO inventory ownership
 */
const F=Object.freeze,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fish=F([{id:'verdant_minnow',name:'Verdant Minnow',rarity:'common',w:55},{id:'silver_carp',name:'Silver Carp',rarity:'uncommon',w:28},{id:'sunscale_bass',name:'Sunscale Bass',rarity:'rare',w:13},{id:'golden_koi',name:'Golden Koi',rarity:'very_rare',w:4}].map(F));
export function mount({getPlayer=()=>globalThis.KeloPlayerPosition?.capture?.()||globalThis.localPlayer,simulation=globalThis.KeloSimulation,render=globalThis.KeloRender,camera=globalThis.KeloCamera}={}){
 if(!simulation?.after||!render?.afterFrame||!globalThis.KeloContainers)throw Error('FISHING_FOUNDATION_UNAVAILABLE');
 const p=getPlayer?.()||{x:1400,y:1480},spot=F({x:(+p.x||1400)-170,y:(+p.y||1480)+150});let state='IDLE',biteAt=0,deadline=0,marker=.1,dir=1,hits=0,last=performance.now(),caught=null;
 const btn=document.createElement('button');btn.type='button';btn.hidden=true;btn.style.cssText='position:fixed;left:50%;bottom:max(92px,calc(env(safe-area-inset-bottom) + 78px));transform:translateX(-50%);z-index:2147482375;min-height:50px;padding:10px 18px;border-radius:16px;border:1px solid rgba(150,205,220,.7);background:rgba(8,18,24,.95);color:#fff;font:850 13px -apple-system,sans-serif;touch-action:manipulation';document.body.appendChild(btn);
 const mini=document.createElement('div');mini.hidden=true;mini.style.cssText='position:fixed;left:50%;bottom:max(151px,calc(env(safe-area-inset-bottom) + 137px));transform:translateX(-50%);z-index:2147482374;width:min(300px,78vw);padding:10px;border-radius:15px;background:rgba(5,13,18,.92);color:#fff;font:750 12px -apple-system,sans-serif;pointer-events:none';mini.innerHTML='<div data-t style="margin-bottom:7px"></div><div style="height:16px;border-radius:9px;background:#27343a;position:relative;overflow:hidden"><i style="position:absolute;left:40%;width:20%;height:100%;background:#6d8b65"></i><i data-m style="position:absolute;top:0;width:5px;height:100%;background:#fff"></i></div>';document.body.appendChild(mini);
 function near(){const q=getPlayer?.();return q&&Math.hypot((+q.x||0)-spot.x,(+q.y||0)-spot.y)<=145}
 function reward(){let n=Math.random()*100,pick=fish[0];for(const f of fish){if(n<f.w){pick=f;break}n-=f.w}const r=globalThis.KeloContainers.receiveItem('backpack',{resourceId:pick.id,templateId:pick.id,kind:'fish',name:pick.name,rarity:pick.rarity,quantity:1,maxStack:20,stackKey:'fish:'+pick.id,source:'verdantia-fishing'},{allowMerge:true});if(r.ok){caught=pick;globalThis.KeloEvents?.emit?.('FISH_CAUGHT',{fishId:pick.id,rarity:pick.rarity})}return r}
 function reset(){state='IDLE';hits=0;mini.hidden=true}
 function action(){const now=Date.now();if(state==='IDLE'){state='WAIT';biteAt=now+1800+Math.random()*2600;return}if(state==='BITE'){state='REEL';deadline=now+6500;hits=0;marker=.1;mini.hidden=false;return}if(state==='REEL'){if(marker>=.4&&marker<=.6){hits++;if(hits>=3){const r=reward();btn.textContent=r.ok?'🐟 '+caught.name:'Mochila llena';reset()}}else deadline-=850}}
 btn.addEventListener('pointerdown',e=>e.stopPropagation());btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();action()});
 function tick(){const now=Date.now(),q=near();btn.hidden=!q;if(!q&&state!=='IDLE')reset();if(state==='IDLE'&&q)btn.textContent='🎣 Lanzar caña';if(state==='WAIT'){btn.textContent='🎣 Esperando picada…';if(now>=biteAt){state='BITE';deadline=now+1800}}if(state==='BITE'){btn.textContent='❗ ¡PICÓ! Enganchar';if(now>deadline)reset()}if(state==='REEL'){if(now>deadline){btn.textContent='Se escapó';reset();return}const t=performance.now(),dt=Math.min(.05,(t-last)/1000);last=t;marker=clamp(marker+dir*dt*.95,0,1);if(marker>=1)dir=-1;if(marker<=0)dir=1;mini.querySelector('[data-m]').style.left=(marker*100)+'%';mini.querySelector('[data-t]').textContent='Mantén la zona · '+hits+'/3 · '+Math.ceil((deadline-now)/1000)+'s';btn.textContent='🎣 RECOGER'}}
 function draw(x){const c=x?.ctx||globalThis.ctx;if(!c||!camera?.worldToScreen)return;const pt=camera.worldToScreen(spot.x,spot.y);c.save();c.translate(pt.x,pt.y);c.fillStyle='rgba(43,126,154,.72)';c.beginPath();c.ellipse(0,0,92,55,0,0,Math.PI*2);c.fill();c.strokeStyle='rgba(170,230,235,.65)';c.lineWidth=2;for(let i=0;i<3;i++){c.beginPath();c.ellipse(0,0,32+i*20,15+i*12,0,0,Math.PI*2);c.stroke()}c.fillStyle='#fff';c.font='800 11px sans-serif';c.textAlign='center';c.fillText('Zona de pesca',0,-66);if(state!=='IDLE'){c.strokeStyle='#d7d2a1';c.beginPath();c.moveTo(0,-20);c.lineTo(18,5);c.stroke();c.fillStyle='#d3aa52';c.beginPath();c.arc(18,5,4,0,Math.PI*2);c.fill()}c.restore()}
 const sh=simulation.after('KeloFishingLive',tick,9260),rh=render.afterFrame('KeloFishingLive',draw,9260);tick();return F({spot,getState:()=>F({state,hits,caught}),destroy(){simulation.unregister?.(sh);render.unregister?.(rh);btn.remove();mini.remove()}});
}
